/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReauthRouteImport } from './routes/reauth'
import { Route as LpRouteImport } from './routes/lp'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ColumnRouteImport } from './routes/column'
import { Route as AboutRouteImport } from './routes/about'
import { Route as MainRouteImport } from './routes/_main'
import { Route as ContentRouteImport } from './routes/_content'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MessageUserIdRouteImport } from './routes/message.$userId'
import { Route as LpTransitionRouteImport } from './routes/lp.transition'
import { Route as LpReviewRouteImport } from './routes/lp.review'
import { Route as LpPromotionRouteImport } from './routes/lp.promotion'
import { Route as LpLovenseFullcontrolRouteImport } from './routes/lp.lovense-fullcontrol'
import { Route as LpJukujoRouteImport } from './routes/lp.jukujo'
import { Route as LpFreePointsRouteImport } from './routes/lp.free-points'
import { Route as LpFleaMarketRouteImport } from './routes/lp.flea-market'
import { Route as LpAmateurRouteImport } from './routes/lp.amateur'
import { Route as LineCallbackRouteImport } from './routes/line.callback'
import { Route as Column13_xxxRouteImport } from './routes/column.13_xxx'
import { Route as Column12_fetishRouteImport } from './routes/column.12_fetish'
import { Route as Column11_smRouteImport } from './routes/column.11_sm'
import { Route as Column10_meganeRouteImport } from './routes/column.10_megane'
import { Route as Column09_loliRouteImport } from './routes/column.09_loli'
import { Route as Column08_galRouteImport } from './routes/column.08_gal'
import { Route as Column07_idolRouteImport } from './routes/column.07_idol'
import { Route as Column06_cosplayRouteImport } from './routes/column.06_cosplay'
import { Route as Column05_nurseRouteImport } from './routes/column.05_nurse'
import { Route as Column04_olRouteImport } from './routes/column.04_ol'
import { Route as Column03_tumaRouteImport } from './routes/column.03_tuma'
import { Route as Column02_jukujoRouteImport } from './routes/column.02_jukujo'
import { Route as Column01_amateurRouteImport } from './routes/column.01_amateur'
import { Route as MainVideoListRouteImport } from './routes/_main/video-list'
import { Route as MainSettingRouteImport } from './routes/_main/setting'
import { Route as MainSearchRouteImport } from './routes/_main/search'
import { Route as MainRankingRouteImport } from './routes/_main/ranking'
import { Route as MainQuickchargeRouteImport } from './routes/_main/quickcharge'
import { Route as MainPurchaseRouteImport } from './routes/_main/purchase'
import { Route as MainPremiumDailybonusRouteImport } from './routes/_main/premium-dailybonus'
import { Route as MainPointHowtoRouteImport } from './routes/_main/point-howto'
import { Route as MainOnboardingRouteImport } from './routes/_main/onboarding'
import { Route as MainNotificationRouteImport } from './routes/_main/notification'
import { Route as MainMyPageRouteImport } from './routes/_main/my-page'
import { Route as MainLovenseRouteImport } from './routes/_main/lovense'
import { Route as MainGalleryRouteImport } from './routes/_main/gallery'
import { Route as MainFootprintListRouteImport } from './routes/_main/footprint-list'
import { Route as MainFleamarketRouteImport } from './routes/_main/fleamarket'
import { Route as MainFavoriteListRouteImport } from './routes/_main/favorite-list'
import { Route as MainEditProfileRouteImport } from './routes/_main/edit-profile'
import { Route as MainDailyBonusRouteImport } from './routes/_main/daily-bonus'
import { Route as MainConversationRouteImport } from './routes/_main/conversation'
import { Route as MainCallrequestRouteImport } from './routes/_main/callrequest'
import { Route as MainCallhistoryListRouteImport } from './routes/_main/callhistory-list'
import { Route as MainBookmarkListRouteImport } from './routes/_main/bookmark-list'
import { Route as MainBoardRouteImport } from './routes/_main/board'
import { Route as MainBlockRouteImport } from './routes/_main/block'
import { Route as ContentTutoRouteImport } from './routes/_content/tuto'
import { Route as ContentTosRouteImport } from './routes/_content/tos'
import { Route as ContentSitemapRouteImport } from './routes/_content/sitemap'
import { Route as ContentPrivacyRouteImport } from './routes/_content/privacy'
import { Route as ContentNewsRouteImport } from './routes/_content/news'
import { Route as ContentFaqRouteImport } from './routes/_content/faq'
import { Route as ContentCommerceRouteImport } from './routes/_content/commerce'
import { Route as ContentApproachRouteImport } from './routes/_content/approach'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthPhoneVerificationRouteImport } from './routes/_auth/phone-verification'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthConfirmMailRouteImport } from './routes/_auth/confirm-mail'
import { Route as ProfileVideoCallBroadcasterPartnerIdRouteImport } from './routes/profile.video-call-broadcaster.$partnerId'
import { Route as ProfileUnbroadcasterPartnerIdRouteImport } from './routes/profile.unbroadcaster.$partnerId'
import { Route as ProfileLiveBroadcasterPartnerIdRouteImport } from './routes/profile.live-broadcaster.$partnerId'
import { Route as ProfileDetailPartnerIdRouteImport } from './routes/profile.detail.$partnerId'
import { Route as ProfileChannelPartnerIdRouteImport } from './routes/profile.channel.$partnerId'
import { Route as OutgoingCallTypeUserIdRouteImport } from './routes/outgoing.$callType.$userId'
import { Route as IncomingCallTypeUserIdRouteImport } from './routes/incoming.$callType.$userId'
import { Route as MainSettingRegisterMailRouteImport } from './routes/_main/setting.register-mail'
import { Route as MainSettingNotificationSettingRouteImport } from './routes/_main/setting.notificationSetting'
import { Route as MainSettingChangePasswordRouteImport } from './routes/_main/setting.change-password'
import { Route as MainSettingChangeMailRouteImport } from './routes/_main/setting.change-mail'
import { Route as MainSearchResultRouteImport } from './routes/_main/search.result'
import { Route as MainPurchasePaymentSuccessRouteImport } from './routes/_main/purchase.payment-success'
import { Route as MainGirlsLiveListRouteImport } from './routes/_main/girls.live-list'
import { Route as MainGirlsAllRouteImport } from './routes/_main/girls.all'
import { Route as MainGalleryRankingRouteImport } from './routes/_main/gallery.ranking'
import { Route as MainGalleryAllRouteImport } from './routes/_main/gallery.all'
import { Route as MainFleamarketTodosRouteImport } from './routes/_main/fleamarket.todos'
import { Route as MainFleamarketSellerIdRouteImport } from './routes/_main/fleamarket.$sellerId'
import { Route as ContentTutoVideochatRouteImport } from './routes/_content/tuto.videochat'
import { Route as ContentTutoVideocallRouteImport } from './routes/_content/tuto.videocall'
import { Route as ContentTutoChatRouteImport } from './routes/_content/tuto.chat'
import { Route as ContentFaqPointRouteImport } from './routes/_content/faq.point'
import { Route as ContentFaqGirlsRouteImport } from './routes/_content/faq.girls'
import { Route as ContentFaqFleamarketRouteImport } from './routes/_content/faq.fleamarket'
import { Route as ContentFaqConnectionRouteImport } from './routes/_content/faq.connection'
import { Route as ContentFaqBenefitsRouteImport } from './routes/_content/faq.benefits'
import { Route as ContentFaqBeginnerRouteImport } from './routes/_content/faq.beginner'
import { Route as ContentFaqAccountRouteImport } from './routes/_content/faq.account'
import { Route as MainMissionOnboardingAddLineFriendRouteImport } from './routes/_main/mission.onboarding.add-line-friend'
import { Route as MainFleamarketTransactionTransactionIdRouteImport } from './routes/_main/fleamarket.transaction.$transactionId'
import { Route as MainFleamarketPurchaseConfirmationItemIdRouteImport } from './routes/_main/fleamarket.purchase-confirmation.$itemId'
import { Route as MainFleamarketItemItemIdRouteImport } from './routes/_main/fleamarket.item.$itemId'

const ReauthRoute = ReauthRouteImport.update({
  id: '/reauth',
  path: '/reauth',
  getParentRoute: () => rootRouteImport,
} as any)
const LpRoute = LpRouteImport.update({
  id: '/lp',
  path: '/lp',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ColumnRoute = ColumnRouteImport.update({
  id: '/column',
  path: '/column',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/_content',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessageUserIdRoute = MessageUserIdRouteImport.update({
  id: '/message/$userId',
  path: '/message/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const LpTransitionRoute = LpTransitionRouteImport.update({
  id: '/transition',
  path: '/transition',
  getParentRoute: () => LpRoute,
} as any)
const LpReviewRoute = LpReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => LpRoute,
} as any)
const LpPromotionRoute = LpPromotionRouteImport.update({
  id: '/promotion',
  path: '/promotion',
  getParentRoute: () => LpRoute,
} as any)
const LpLovenseFullcontrolRoute = LpLovenseFullcontrolRouteImport.update({
  id: '/lovense-fullcontrol',
  path: '/lovense-fullcontrol',
  getParentRoute: () => LpRoute,
} as any)
const LpJukujoRoute = LpJukujoRouteImport.update({
  id: '/jukujo',
  path: '/jukujo',
  getParentRoute: () => LpRoute,
} as any)
const LpFreePointsRoute = LpFreePointsRouteImport.update({
  id: '/free-points',
  path: '/free-points',
  getParentRoute: () => LpRoute,
} as any)
const LpFleaMarketRoute = LpFleaMarketRouteImport.update({
  id: '/flea-market',
  path: '/flea-market',
  getParentRoute: () => LpRoute,
} as any)
const LpAmateurRoute = LpAmateurRouteImport.update({
  id: '/amateur',
  path: '/amateur',
  getParentRoute: () => LpRoute,
} as any)
const LineCallbackRoute = LineCallbackRouteImport.update({
  id: '/line/callback',
  path: '/line/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const Column13_xxxRoute = Column13_xxxRouteImport.update({
  id: '/13_xxx',
  path: '/13_xxx',
  getParentRoute: () => ColumnRoute,
} as any)
const Column12_fetishRoute = Column12_fetishRouteImport.update({
  id: '/12_fetish',
  path: '/12_fetish',
  getParentRoute: () => ColumnRoute,
} as any)
const Column11_smRoute = Column11_smRouteImport.update({
  id: '/11_sm',
  path: '/11_sm',
  getParentRoute: () => ColumnRoute,
} as any)
const Column10_meganeRoute = Column10_meganeRouteImport.update({
  id: '/10_megane',
  path: '/10_megane',
  getParentRoute: () => ColumnRoute,
} as any)
const Column09_loliRoute = Column09_loliRouteImport.update({
  id: '/09_loli',
  path: '/09_loli',
  getParentRoute: () => ColumnRoute,
} as any)
const Column08_galRoute = Column08_galRouteImport.update({
  id: '/08_gal',
  path: '/08_gal',
  getParentRoute: () => ColumnRoute,
} as any)
const Column07_idolRoute = Column07_idolRouteImport.update({
  id: '/07_idol',
  path: '/07_idol',
  getParentRoute: () => ColumnRoute,
} as any)
const Column06_cosplayRoute = Column06_cosplayRouteImport.update({
  id: '/06_cosplay',
  path: '/06_cosplay',
  getParentRoute: () => ColumnRoute,
} as any)
const Column05_nurseRoute = Column05_nurseRouteImport.update({
  id: '/05_nurse',
  path: '/05_nurse',
  getParentRoute: () => ColumnRoute,
} as any)
const Column04_olRoute = Column04_olRouteImport.update({
  id: '/04_ol',
  path: '/04_ol',
  getParentRoute: () => ColumnRoute,
} as any)
const Column03_tumaRoute = Column03_tumaRouteImport.update({
  id: '/03_tuma',
  path: '/03_tuma',
  getParentRoute: () => ColumnRoute,
} as any)
const Column02_jukujoRoute = Column02_jukujoRouteImport.update({
  id: '/02_jukujo',
  path: '/02_jukujo',
  getParentRoute: () => ColumnRoute,
} as any)
const Column01_amateurRoute = Column01_amateurRouteImport.update({
  id: '/01_amateur',
  path: '/01_amateur',
  getParentRoute: () => ColumnRoute,
} as any)
const MainVideoListRoute = MainVideoListRouteImport.update({
  id: '/video-list',
  path: '/video-list',
  getParentRoute: () => MainRoute,
} as any)
const MainSettingRoute = MainSettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => MainRoute,
} as any)
const MainSearchRoute = MainSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => MainRoute,
} as any)
const MainRankingRoute = MainRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => MainRoute,
} as any)
const MainQuickchargeRoute = MainQuickchargeRouteImport.update({
  id: '/quickcharge',
  path: '/quickcharge',
  getParentRoute: () => MainRoute,
} as any)
const MainPurchaseRoute = MainPurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => MainRoute,
} as any)
const MainPremiumDailybonusRoute = MainPremiumDailybonusRouteImport.update({
  id: '/premium-dailybonus',
  path: '/premium-dailybonus',
  getParentRoute: () => MainRoute,
} as any)
const MainPointHowtoRoute = MainPointHowtoRouteImport.update({
  id: '/point-howto',
  path: '/point-howto',
  getParentRoute: () => MainRoute,
} as any)
const MainOnboardingRoute = MainOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => MainRoute,
} as any)
const MainNotificationRoute = MainNotificationRouteImport.update({
  id: '/notification',
  path: '/notification',
  getParentRoute: () => MainRoute,
} as any)
const MainMyPageRoute = MainMyPageRouteImport.update({
  id: '/my-page',
  path: '/my-page',
  getParentRoute: () => MainRoute,
} as any)
const MainLovenseRoute = MainLovenseRouteImport.update({
  id: '/lovense',
  path: '/lovense',
  getParentRoute: () => MainRoute,
} as any)
const MainGalleryRoute = MainGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => MainRoute,
} as any)
const MainFootprintListRoute = MainFootprintListRouteImport.update({
  id: '/footprint-list',
  path: '/footprint-list',
  getParentRoute: () => MainRoute,
} as any)
const MainFleamarketRoute = MainFleamarketRouteImport.update({
  id: '/fleamarket',
  path: '/fleamarket',
  getParentRoute: () => MainRoute,
} as any)
const MainFavoriteListRoute = MainFavoriteListRouteImport.update({
  id: '/favorite-list',
  path: '/favorite-list',
  getParentRoute: () => MainRoute,
} as any)
const MainEditProfileRoute = MainEditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => MainRoute,
} as any)
const MainDailyBonusRoute = MainDailyBonusRouteImport.update({
  id: '/daily-bonus',
  path: '/daily-bonus',
  getParentRoute: () => MainRoute,
} as any)
const MainConversationRoute = MainConversationRouteImport.update({
  id: '/conversation',
  path: '/conversation',
  getParentRoute: () => MainRoute,
} as any)
const MainCallrequestRoute = MainCallrequestRouteImport.update({
  id: '/callrequest',
  path: '/callrequest',
  getParentRoute: () => MainRoute,
} as any)
const MainCallhistoryListRoute = MainCallhistoryListRouteImport.update({
  id: '/callhistory-list',
  path: '/callhistory-list',
  getParentRoute: () => MainRoute,
} as any)
const MainBookmarkListRoute = MainBookmarkListRouteImport.update({
  id: '/bookmark-list',
  path: '/bookmark-list',
  getParentRoute: () => MainRoute,
} as any)
const MainBoardRoute = MainBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => MainRoute,
} as any)
const MainBlockRoute = MainBlockRouteImport.update({
  id: '/block',
  path: '/block',
  getParentRoute: () => MainRoute,
} as any)
const ContentTutoRoute = ContentTutoRouteImport.update({
  id: '/tuto',
  path: '/tuto',
  getParentRoute: () => ContentRoute,
} as any)
const ContentTosRoute = ContentTosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => ContentRoute,
} as any)
const ContentSitemapRoute = ContentSitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => ContentRoute,
} as any)
const ContentPrivacyRoute = ContentPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => ContentRoute,
} as any)
const ContentNewsRoute = ContentNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => ContentRoute,
} as any)
const ContentFaqRoute = ContentFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => ContentRoute,
} as any)
const ContentCommerceRoute = ContentCommerceRouteImport.update({
  id: '/commerce',
  path: '/commerce',
  getParentRoute: () => ContentRoute,
} as any)
const ContentApproachRoute = ContentApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => ContentRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPhoneVerificationRoute = AuthPhoneVerificationRouteImport.update({
  id: '/phone-verification',
  path: '/phone-verification',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConfirmMailRoute = AuthConfirmMailRouteImport.update({
  id: '/confirm-mail',
  path: '/confirm-mail',
  getParentRoute: () => AuthRoute,
} as any)
const ProfileVideoCallBroadcasterPartnerIdRoute =
  ProfileVideoCallBroadcasterPartnerIdRouteImport.update({
    id: '/profile/video-call-broadcaster/$partnerId',
    path: '/profile/video-call-broadcaster/$partnerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfileUnbroadcasterPartnerIdRoute =
  ProfileUnbroadcasterPartnerIdRouteImport.update({
    id: '/profile/unbroadcaster/$partnerId',
    path: '/profile/unbroadcaster/$partnerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfileLiveBroadcasterPartnerIdRoute =
  ProfileLiveBroadcasterPartnerIdRouteImport.update({
    id: '/profile/live-broadcaster/$partnerId',
    path: '/profile/live-broadcaster/$partnerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfileDetailPartnerIdRoute = ProfileDetailPartnerIdRouteImport.update({
  id: '/profile/detail/$partnerId',
  path: '/profile/detail/$partnerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileChannelPartnerIdRoute = ProfileChannelPartnerIdRouteImport.update({
  id: '/profile/channel/$partnerId',
  path: '/profile/channel/$partnerId',
  getParentRoute: () => rootRouteImport,
} as any)
const OutgoingCallTypeUserIdRoute = OutgoingCallTypeUserIdRouteImport.update({
  id: '/outgoing/$callType/$userId',
  path: '/outgoing/$callType/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomingCallTypeUserIdRoute = IncomingCallTypeUserIdRouteImport.update({
  id: '/incoming/$callType/$userId',
  path: '/incoming/$callType/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const MainSettingRegisterMailRoute = MainSettingRegisterMailRouteImport.update({
  id: '/register-mail',
  path: '/register-mail',
  getParentRoute: () => MainSettingRoute,
} as any)
const MainSettingNotificationSettingRoute =
  MainSettingNotificationSettingRouteImport.update({
    id: '/notificationSetting',
    path: '/notificationSetting',
    getParentRoute: () => MainSettingRoute,
  } as any)
const MainSettingChangePasswordRoute =
  MainSettingChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => MainSettingRoute,
  } as any)
const MainSettingChangeMailRoute = MainSettingChangeMailRouteImport.update({
  id: '/change-mail',
  path: '/change-mail',
  getParentRoute: () => MainSettingRoute,
} as any)
const MainSearchResultRoute = MainSearchResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => MainSearchRoute,
} as any)
const MainPurchasePaymentSuccessRoute =
  MainPurchasePaymentSuccessRouteImport.update({
    id: '/payment-success',
    path: '/payment-success',
    getParentRoute: () => MainPurchaseRoute,
  } as any)
const MainGirlsLiveListRoute = MainGirlsLiveListRouteImport.update({
  id: '/girls/live-list',
  path: '/girls/live-list',
  getParentRoute: () => MainRoute,
} as any)
const MainGirlsAllRoute = MainGirlsAllRouteImport.update({
  id: '/girls/all',
  path: '/girls/all',
  getParentRoute: () => MainRoute,
} as any)
const MainGalleryRankingRoute = MainGalleryRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => MainGalleryRoute,
} as any)
const MainGalleryAllRoute = MainGalleryAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => MainGalleryRoute,
} as any)
const MainFleamarketTodosRoute = MainFleamarketTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => MainFleamarketRoute,
} as any)
const MainFleamarketSellerIdRoute = MainFleamarketSellerIdRouteImport.update({
  id: '/$sellerId',
  path: '/$sellerId',
  getParentRoute: () => MainFleamarketRoute,
} as any)
const ContentTutoVideochatRoute = ContentTutoVideochatRouteImport.update({
  id: '/videochat',
  path: '/videochat',
  getParentRoute: () => ContentTutoRoute,
} as any)
const ContentTutoVideocallRoute = ContentTutoVideocallRouteImport.update({
  id: '/videocall',
  path: '/videocall',
  getParentRoute: () => ContentTutoRoute,
} as any)
const ContentTutoChatRoute = ContentTutoChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ContentTutoRoute,
} as any)
const ContentFaqPointRoute = ContentFaqPointRouteImport.update({
  id: '/point',
  path: '/point',
  getParentRoute: () => ContentFaqRoute,
} as any)
const ContentFaqGirlsRoute = ContentFaqGirlsRouteImport.update({
  id: '/girls',
  path: '/girls',
  getParentRoute: () => ContentFaqRoute,
} as any)
const ContentFaqFleamarketRoute = ContentFaqFleamarketRouteImport.update({
  id: '/fleamarket',
  path: '/fleamarket',
  getParentRoute: () => ContentFaqRoute,
} as any)
const ContentFaqConnectionRoute = ContentFaqConnectionRouteImport.update({
  id: '/connection',
  path: '/connection',
  getParentRoute: () => ContentFaqRoute,
} as any)
const ContentFaqBenefitsRoute = ContentFaqBenefitsRouteImport.update({
  id: '/benefits',
  path: '/benefits',
  getParentRoute: () => ContentFaqRoute,
} as any)
const ContentFaqBeginnerRoute = ContentFaqBeginnerRouteImport.update({
  id: '/beginner',
  path: '/beginner',
  getParentRoute: () => ContentFaqRoute,
} as any)
const ContentFaqAccountRoute = ContentFaqAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ContentFaqRoute,
} as any)
const MainMissionOnboardingAddLineFriendRoute =
  MainMissionOnboardingAddLineFriendRouteImport.update({
    id: '/mission/onboarding/add-line-friend',
    path: '/mission/onboarding/add-line-friend',
    getParentRoute: () => MainRoute,
  } as any)
const MainFleamarketTransactionTransactionIdRoute =
  MainFleamarketTransactionTransactionIdRouteImport.update({
    id: '/transaction/$transactionId',
    path: '/transaction/$transactionId',
    getParentRoute: () => MainFleamarketRoute,
  } as any)
const MainFleamarketPurchaseConfirmationItemIdRoute =
  MainFleamarketPurchaseConfirmationItemIdRouteImport.update({
    id: '/purchase-confirmation/$itemId',
    path: '/purchase-confirmation/$itemId',
    getParentRoute: () => MainFleamarketRoute,
  } as any)
const MainFleamarketItemItemIdRoute =
  MainFleamarketItemItemIdRouteImport.update({
    id: '/item/$itemId',
    path: '/item/$itemId',
    getParentRoute: () => MainFleamarketRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/column': typeof ColumnRouteWithChildren
  '/health': typeof HealthRoute
  '/lp': typeof LpRouteWithChildren
  '/reauth': typeof ReauthRoute
  '/confirm-mail': typeof AuthConfirmMailRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/phone-verification': typeof AuthPhoneVerificationRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/approach': typeof ContentApproachRoute
  '/commerce': typeof ContentCommerceRoute
  '/faq': typeof ContentFaqRouteWithChildren
  '/news': typeof ContentNewsRoute
  '/privacy': typeof ContentPrivacyRoute
  '/sitemap': typeof ContentSitemapRoute
  '/tos': typeof ContentTosRoute
  '/tuto': typeof ContentTutoRouteWithChildren
  '/block': typeof MainBlockRoute
  '/board': typeof MainBoardRoute
  '/bookmark-list': typeof MainBookmarkListRoute
  '/callhistory-list': typeof MainCallhistoryListRoute
  '/callrequest': typeof MainCallrequestRoute
  '/conversation': typeof MainConversationRoute
  '/daily-bonus': typeof MainDailyBonusRoute
  '/edit-profile': typeof MainEditProfileRoute
  '/favorite-list': typeof MainFavoriteListRoute
  '/fleamarket': typeof MainFleamarketRouteWithChildren
  '/footprint-list': typeof MainFootprintListRoute
  '/gallery': typeof MainGalleryRouteWithChildren
  '/lovense': typeof MainLovenseRoute
  '/my-page': typeof MainMyPageRoute
  '/notification': typeof MainNotificationRoute
  '/onboarding': typeof MainOnboardingRoute
  '/point-howto': typeof MainPointHowtoRoute
  '/premium-dailybonus': typeof MainPremiumDailybonusRoute
  '/purchase': typeof MainPurchaseRouteWithChildren
  '/quickcharge': typeof MainQuickchargeRoute
  '/ranking': typeof MainRankingRoute
  '/search': typeof MainSearchRouteWithChildren
  '/setting': typeof MainSettingRouteWithChildren
  '/video-list': typeof MainVideoListRoute
  '/column/01_amateur': typeof Column01_amateurRoute
  '/column/02_jukujo': typeof Column02_jukujoRoute
  '/column/03_tuma': typeof Column03_tumaRoute
  '/column/04_ol': typeof Column04_olRoute
  '/column/05_nurse': typeof Column05_nurseRoute
  '/column/06_cosplay': typeof Column06_cosplayRoute
  '/column/07_idol': typeof Column07_idolRoute
  '/column/08_gal': typeof Column08_galRoute
  '/column/09_loli': typeof Column09_loliRoute
  '/column/10_megane': typeof Column10_meganeRoute
  '/column/11_sm': typeof Column11_smRoute
  '/column/12_fetish': typeof Column12_fetishRoute
  '/column/13_xxx': typeof Column13_xxxRoute
  '/line/callback': typeof LineCallbackRoute
  '/lp/amateur': typeof LpAmateurRoute
  '/lp/flea-market': typeof LpFleaMarketRoute
  '/lp/free-points': typeof LpFreePointsRoute
  '/lp/jukujo': typeof LpJukujoRoute
  '/lp/lovense-fullcontrol': typeof LpLovenseFullcontrolRoute
  '/lp/promotion': typeof LpPromotionRoute
  '/lp/review': typeof LpReviewRoute
  '/lp/transition': typeof LpTransitionRoute
  '/message/$userId': typeof MessageUserIdRoute
  '/faq/account': typeof ContentFaqAccountRoute
  '/faq/beginner': typeof ContentFaqBeginnerRoute
  '/faq/benefits': typeof ContentFaqBenefitsRoute
  '/faq/connection': typeof ContentFaqConnectionRoute
  '/faq/fleamarket': typeof ContentFaqFleamarketRoute
  '/faq/girls': typeof ContentFaqGirlsRoute
  '/faq/point': typeof ContentFaqPointRoute
  '/tuto/chat': typeof ContentTutoChatRoute
  '/tuto/videocall': typeof ContentTutoVideocallRoute
  '/tuto/videochat': typeof ContentTutoVideochatRoute
  '/fleamarket/$sellerId': typeof MainFleamarketSellerIdRoute
  '/fleamarket/todos': typeof MainFleamarketTodosRoute
  '/gallery/all': typeof MainGalleryAllRoute
  '/gallery/ranking': typeof MainGalleryRankingRoute
  '/girls/all': typeof MainGirlsAllRoute
  '/girls/live-list': typeof MainGirlsLiveListRoute
  '/purchase/payment-success': typeof MainPurchasePaymentSuccessRoute
  '/search/result': typeof MainSearchResultRoute
  '/setting/change-mail': typeof MainSettingChangeMailRoute
  '/setting/change-password': typeof MainSettingChangePasswordRoute
  '/setting/notificationSetting': typeof MainSettingNotificationSettingRoute
  '/setting/register-mail': typeof MainSettingRegisterMailRoute
  '/incoming/$callType/$userId': typeof IncomingCallTypeUserIdRoute
  '/outgoing/$callType/$userId': typeof OutgoingCallTypeUserIdRoute
  '/profile/channel/$partnerId': typeof ProfileChannelPartnerIdRoute
  '/profile/detail/$partnerId': typeof ProfileDetailPartnerIdRoute
  '/profile/live-broadcaster/$partnerId': typeof ProfileLiveBroadcasterPartnerIdRoute
  '/profile/unbroadcaster/$partnerId': typeof ProfileUnbroadcasterPartnerIdRoute
  '/profile/video-call-broadcaster/$partnerId': typeof ProfileVideoCallBroadcasterPartnerIdRoute
  '/fleamarket/item/$itemId': typeof MainFleamarketItemItemIdRoute
  '/fleamarket/purchase-confirmation/$itemId': typeof MainFleamarketPurchaseConfirmationItemIdRoute
  '/fleamarket/transaction/$transactionId': typeof MainFleamarketTransactionTransactionIdRoute
  '/mission/onboarding/add-line-friend': typeof MainMissionOnboardingAddLineFriendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/column': typeof ColumnRouteWithChildren
  '/health': typeof HealthRoute
  '/lp': typeof LpRouteWithChildren
  '/reauth': typeof ReauthRoute
  '/confirm-mail': typeof AuthConfirmMailRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/phone-verification': typeof AuthPhoneVerificationRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/approach': typeof ContentApproachRoute
  '/commerce': typeof ContentCommerceRoute
  '/faq': typeof ContentFaqRouteWithChildren
  '/news': typeof ContentNewsRoute
  '/privacy': typeof ContentPrivacyRoute
  '/sitemap': typeof ContentSitemapRoute
  '/tos': typeof ContentTosRoute
  '/tuto': typeof ContentTutoRouteWithChildren
  '/block': typeof MainBlockRoute
  '/board': typeof MainBoardRoute
  '/bookmark-list': typeof MainBookmarkListRoute
  '/callhistory-list': typeof MainCallhistoryListRoute
  '/callrequest': typeof MainCallrequestRoute
  '/conversation': typeof MainConversationRoute
  '/daily-bonus': typeof MainDailyBonusRoute
  '/edit-profile': typeof MainEditProfileRoute
  '/favorite-list': typeof MainFavoriteListRoute
  '/fleamarket': typeof MainFleamarketRouteWithChildren
  '/footprint-list': typeof MainFootprintListRoute
  '/gallery': typeof MainGalleryRouteWithChildren
  '/lovense': typeof MainLovenseRoute
  '/my-page': typeof MainMyPageRoute
  '/notification': typeof MainNotificationRoute
  '/onboarding': typeof MainOnboardingRoute
  '/point-howto': typeof MainPointHowtoRoute
  '/premium-dailybonus': typeof MainPremiumDailybonusRoute
  '/purchase': typeof MainPurchaseRouteWithChildren
  '/quickcharge': typeof MainQuickchargeRoute
  '/ranking': typeof MainRankingRoute
  '/search': typeof MainSearchRouteWithChildren
  '/setting': typeof MainSettingRouteWithChildren
  '/video-list': typeof MainVideoListRoute
  '/column/01_amateur': typeof Column01_amateurRoute
  '/column/02_jukujo': typeof Column02_jukujoRoute
  '/column/03_tuma': typeof Column03_tumaRoute
  '/column/04_ol': typeof Column04_olRoute
  '/column/05_nurse': typeof Column05_nurseRoute
  '/column/06_cosplay': typeof Column06_cosplayRoute
  '/column/07_idol': typeof Column07_idolRoute
  '/column/08_gal': typeof Column08_galRoute
  '/column/09_loli': typeof Column09_loliRoute
  '/column/10_megane': typeof Column10_meganeRoute
  '/column/11_sm': typeof Column11_smRoute
  '/column/12_fetish': typeof Column12_fetishRoute
  '/column/13_xxx': typeof Column13_xxxRoute
  '/line/callback': typeof LineCallbackRoute
  '/lp/amateur': typeof LpAmateurRoute
  '/lp/flea-market': typeof LpFleaMarketRoute
  '/lp/free-points': typeof LpFreePointsRoute
  '/lp/jukujo': typeof LpJukujoRoute
  '/lp/lovense-fullcontrol': typeof LpLovenseFullcontrolRoute
  '/lp/promotion': typeof LpPromotionRoute
  '/lp/review': typeof LpReviewRoute
  '/lp/transition': typeof LpTransitionRoute
  '/message/$userId': typeof MessageUserIdRoute
  '/faq/account': typeof ContentFaqAccountRoute
  '/faq/beginner': typeof ContentFaqBeginnerRoute
  '/faq/benefits': typeof ContentFaqBenefitsRoute
  '/faq/connection': typeof ContentFaqConnectionRoute
  '/faq/fleamarket': typeof ContentFaqFleamarketRoute
  '/faq/girls': typeof ContentFaqGirlsRoute
  '/faq/point': typeof ContentFaqPointRoute
  '/tuto/chat': typeof ContentTutoChatRoute
  '/tuto/videocall': typeof ContentTutoVideocallRoute
  '/tuto/videochat': typeof ContentTutoVideochatRoute
  '/fleamarket/$sellerId': typeof MainFleamarketSellerIdRoute
  '/fleamarket/todos': typeof MainFleamarketTodosRoute
  '/gallery/all': typeof MainGalleryAllRoute
  '/gallery/ranking': typeof MainGalleryRankingRoute
  '/girls/all': typeof MainGirlsAllRoute
  '/girls/live-list': typeof MainGirlsLiveListRoute
  '/purchase/payment-success': typeof MainPurchasePaymentSuccessRoute
  '/search/result': typeof MainSearchResultRoute
  '/setting/change-mail': typeof MainSettingChangeMailRoute
  '/setting/change-password': typeof MainSettingChangePasswordRoute
  '/setting/notificationSetting': typeof MainSettingNotificationSettingRoute
  '/setting/register-mail': typeof MainSettingRegisterMailRoute
  '/incoming/$callType/$userId': typeof IncomingCallTypeUserIdRoute
  '/outgoing/$callType/$userId': typeof OutgoingCallTypeUserIdRoute
  '/profile/channel/$partnerId': typeof ProfileChannelPartnerIdRoute
  '/profile/detail/$partnerId': typeof ProfileDetailPartnerIdRoute
  '/profile/live-broadcaster/$partnerId': typeof ProfileLiveBroadcasterPartnerIdRoute
  '/profile/unbroadcaster/$partnerId': typeof ProfileUnbroadcasterPartnerIdRoute
  '/profile/video-call-broadcaster/$partnerId': typeof ProfileVideoCallBroadcasterPartnerIdRoute
  '/fleamarket/item/$itemId': typeof MainFleamarketItemItemIdRoute
  '/fleamarket/purchase-confirmation/$itemId': typeof MainFleamarketPurchaseConfirmationItemIdRoute
  '/fleamarket/transaction/$transactionId': typeof MainFleamarketTransactionTransactionIdRoute
  '/mission/onboarding/add-line-friend': typeof MainMissionOnboardingAddLineFriendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_content': typeof ContentRouteWithChildren
  '/_main': typeof MainRouteWithChildren
  '/about': typeof AboutRoute
  '/column': typeof ColumnRouteWithChildren
  '/health': typeof HealthRoute
  '/lp': typeof LpRouteWithChildren
  '/reauth': typeof ReauthRoute
  '/_auth/confirm-mail': typeof AuthConfirmMailRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/phone-verification': typeof AuthPhoneVerificationRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_content/approach': typeof ContentApproachRoute
  '/_content/commerce': typeof ContentCommerceRoute
  '/_content/faq': typeof ContentFaqRouteWithChildren
  '/_content/news': typeof ContentNewsRoute
  '/_content/privacy': typeof ContentPrivacyRoute
  '/_content/sitemap': typeof ContentSitemapRoute
  '/_content/tos': typeof ContentTosRoute
  '/_content/tuto': typeof ContentTutoRouteWithChildren
  '/_main/block': typeof MainBlockRoute
  '/_main/board': typeof MainBoardRoute
  '/_main/bookmark-list': typeof MainBookmarkListRoute
  '/_main/callhistory-list': typeof MainCallhistoryListRoute
  '/_main/callrequest': typeof MainCallrequestRoute
  '/_main/conversation': typeof MainConversationRoute
  '/_main/daily-bonus': typeof MainDailyBonusRoute
  '/_main/edit-profile': typeof MainEditProfileRoute
  '/_main/favorite-list': typeof MainFavoriteListRoute
  '/_main/fleamarket': typeof MainFleamarketRouteWithChildren
  '/_main/footprint-list': typeof MainFootprintListRoute
  '/_main/gallery': typeof MainGalleryRouteWithChildren
  '/_main/lovense': typeof MainLovenseRoute
  '/_main/my-page': typeof MainMyPageRoute
  '/_main/notification': typeof MainNotificationRoute
  '/_main/onboarding': typeof MainOnboardingRoute
  '/_main/point-howto': typeof MainPointHowtoRoute
  '/_main/premium-dailybonus': typeof MainPremiumDailybonusRoute
  '/_main/purchase': typeof MainPurchaseRouteWithChildren
  '/_main/quickcharge': typeof MainQuickchargeRoute
  '/_main/ranking': typeof MainRankingRoute
  '/_main/search': typeof MainSearchRouteWithChildren
  '/_main/setting': typeof MainSettingRouteWithChildren
  '/_main/video-list': typeof MainVideoListRoute
  '/column/01_amateur': typeof Column01_amateurRoute
  '/column/02_jukujo': typeof Column02_jukujoRoute
  '/column/03_tuma': typeof Column03_tumaRoute
  '/column/04_ol': typeof Column04_olRoute
  '/column/05_nurse': typeof Column05_nurseRoute
  '/column/06_cosplay': typeof Column06_cosplayRoute
  '/column/07_idol': typeof Column07_idolRoute
  '/column/08_gal': typeof Column08_galRoute
  '/column/09_loli': typeof Column09_loliRoute
  '/column/10_megane': typeof Column10_meganeRoute
  '/column/11_sm': typeof Column11_smRoute
  '/column/12_fetish': typeof Column12_fetishRoute
  '/column/13_xxx': typeof Column13_xxxRoute
  '/line/callback': typeof LineCallbackRoute
  '/lp/amateur': typeof LpAmateurRoute
  '/lp/flea-market': typeof LpFleaMarketRoute
  '/lp/free-points': typeof LpFreePointsRoute
  '/lp/jukujo': typeof LpJukujoRoute
  '/lp/lovense-fullcontrol': typeof LpLovenseFullcontrolRoute
  '/lp/promotion': typeof LpPromotionRoute
  '/lp/review': typeof LpReviewRoute
  '/lp/transition': typeof LpTransitionRoute
  '/message/$userId': typeof MessageUserIdRoute
  '/_content/faq/account': typeof ContentFaqAccountRoute
  '/_content/faq/beginner': typeof ContentFaqBeginnerRoute
  '/_content/faq/benefits': typeof ContentFaqBenefitsRoute
  '/_content/faq/connection': typeof ContentFaqConnectionRoute
  '/_content/faq/fleamarket': typeof ContentFaqFleamarketRoute
  '/_content/faq/girls': typeof ContentFaqGirlsRoute
  '/_content/faq/point': typeof ContentFaqPointRoute
  '/_content/tuto/chat': typeof ContentTutoChatRoute
  '/_content/tuto/videocall': typeof ContentTutoVideocallRoute
  '/_content/tuto/videochat': typeof ContentTutoVideochatRoute
  '/_main/fleamarket/$sellerId': typeof MainFleamarketSellerIdRoute
  '/_main/fleamarket/todos': typeof MainFleamarketTodosRoute
  '/_main/gallery/all': typeof MainGalleryAllRoute
  '/_main/gallery/ranking': typeof MainGalleryRankingRoute
  '/_main/girls/all': typeof MainGirlsAllRoute
  '/_main/girls/live-list': typeof MainGirlsLiveListRoute
  '/_main/purchase/payment-success': typeof MainPurchasePaymentSuccessRoute
  '/_main/search/result': typeof MainSearchResultRoute
  '/_main/setting/change-mail': typeof MainSettingChangeMailRoute
  '/_main/setting/change-password': typeof MainSettingChangePasswordRoute
  '/_main/setting/notificationSetting': typeof MainSettingNotificationSettingRoute
  '/_main/setting/register-mail': typeof MainSettingRegisterMailRoute
  '/incoming/$callType/$userId': typeof IncomingCallTypeUserIdRoute
  '/outgoing/$callType/$userId': typeof OutgoingCallTypeUserIdRoute
  '/profile/channel/$partnerId': typeof ProfileChannelPartnerIdRoute
  '/profile/detail/$partnerId': typeof ProfileDetailPartnerIdRoute
  '/profile/live-broadcaster/$partnerId': typeof ProfileLiveBroadcasterPartnerIdRoute
  '/profile/unbroadcaster/$partnerId': typeof ProfileUnbroadcasterPartnerIdRoute
  '/profile/video-call-broadcaster/$partnerId': typeof ProfileVideoCallBroadcasterPartnerIdRoute
  '/_main/fleamarket/item/$itemId': typeof MainFleamarketItemItemIdRoute
  '/_main/fleamarket/purchase-confirmation/$itemId': typeof MainFleamarketPurchaseConfirmationItemIdRoute
  '/_main/fleamarket/transaction/$transactionId': typeof MainFleamarketTransactionTransactionIdRoute
  '/_main/mission/onboarding/add-line-friend': typeof MainMissionOnboardingAddLineFriendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/column'
    | '/health'
    | '/lp'
    | '/reauth'
    | '/confirm-mail'
    | '/forgot-password'
    | '/login'
    | '/phone-verification'
    | '/reset-password'
    | '/signup'
    | '/approach'
    | '/commerce'
    | '/faq'
    | '/news'
    | '/privacy'
    | '/sitemap'
    | '/tos'
    | '/tuto'
    | '/block'
    | '/board'
    | '/bookmark-list'
    | '/callhistory-list'
    | '/callrequest'
    | '/conversation'
    | '/daily-bonus'
    | '/edit-profile'
    | '/favorite-list'
    | '/fleamarket'
    | '/footprint-list'
    | '/gallery'
    | '/lovense'
    | '/my-page'
    | '/notification'
    | '/onboarding'
    | '/point-howto'
    | '/premium-dailybonus'
    | '/purchase'
    | '/quickcharge'
    | '/ranking'
    | '/search'
    | '/setting'
    | '/video-list'
    | '/column/01_amateur'
    | '/column/02_jukujo'
    | '/column/03_tuma'
    | '/column/04_ol'
    | '/column/05_nurse'
    | '/column/06_cosplay'
    | '/column/07_idol'
    | '/column/08_gal'
    | '/column/09_loli'
    | '/column/10_megane'
    | '/column/11_sm'
    | '/column/12_fetish'
    | '/column/13_xxx'
    | '/line/callback'
    | '/lp/amateur'
    | '/lp/flea-market'
    | '/lp/free-points'
    | '/lp/jukujo'
    | '/lp/lovense-fullcontrol'
    | '/lp/promotion'
    | '/lp/review'
    | '/lp/transition'
    | '/message/$userId'
    | '/faq/account'
    | '/faq/beginner'
    | '/faq/benefits'
    | '/faq/connection'
    | '/faq/fleamarket'
    | '/faq/girls'
    | '/faq/point'
    | '/tuto/chat'
    | '/tuto/videocall'
    | '/tuto/videochat'
    | '/fleamarket/$sellerId'
    | '/fleamarket/todos'
    | '/gallery/all'
    | '/gallery/ranking'
    | '/girls/all'
    | '/girls/live-list'
    | '/purchase/payment-success'
    | '/search/result'
    | '/setting/change-mail'
    | '/setting/change-password'
    | '/setting/notificationSetting'
    | '/setting/register-mail'
    | '/incoming/$callType/$userId'
    | '/outgoing/$callType/$userId'
    | '/profile/channel/$partnerId'
    | '/profile/detail/$partnerId'
    | '/profile/live-broadcaster/$partnerId'
    | '/profile/unbroadcaster/$partnerId'
    | '/profile/video-call-broadcaster/$partnerId'
    | '/fleamarket/item/$itemId'
    | '/fleamarket/purchase-confirmation/$itemId'
    | '/fleamarket/transaction/$transactionId'
    | '/mission/onboarding/add-line-friend'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/column'
    | '/health'
    | '/lp'
    | '/reauth'
    | '/confirm-mail'
    | '/forgot-password'
    | '/login'
    | '/phone-verification'
    | '/reset-password'
    | '/signup'
    | '/approach'
    | '/commerce'
    | '/faq'
    | '/news'
    | '/privacy'
    | '/sitemap'
    | '/tos'
    | '/tuto'
    | '/block'
    | '/board'
    | '/bookmark-list'
    | '/callhistory-list'
    | '/callrequest'
    | '/conversation'
    | '/daily-bonus'
    | '/edit-profile'
    | '/favorite-list'
    | '/fleamarket'
    | '/footprint-list'
    | '/gallery'
    | '/lovense'
    | '/my-page'
    | '/notification'
    | '/onboarding'
    | '/point-howto'
    | '/premium-dailybonus'
    | '/purchase'
    | '/quickcharge'
    | '/ranking'
    | '/search'
    | '/setting'
    | '/video-list'
    | '/column/01_amateur'
    | '/column/02_jukujo'
    | '/column/03_tuma'
    | '/column/04_ol'
    | '/column/05_nurse'
    | '/column/06_cosplay'
    | '/column/07_idol'
    | '/column/08_gal'
    | '/column/09_loli'
    | '/column/10_megane'
    | '/column/11_sm'
    | '/column/12_fetish'
    | '/column/13_xxx'
    | '/line/callback'
    | '/lp/amateur'
    | '/lp/flea-market'
    | '/lp/free-points'
    | '/lp/jukujo'
    | '/lp/lovense-fullcontrol'
    | '/lp/promotion'
    | '/lp/review'
    | '/lp/transition'
    | '/message/$userId'
    | '/faq/account'
    | '/faq/beginner'
    | '/faq/benefits'
    | '/faq/connection'
    | '/faq/fleamarket'
    | '/faq/girls'
    | '/faq/point'
    | '/tuto/chat'
    | '/tuto/videocall'
    | '/tuto/videochat'
    | '/fleamarket/$sellerId'
    | '/fleamarket/todos'
    | '/gallery/all'
    | '/gallery/ranking'
    | '/girls/all'
    | '/girls/live-list'
    | '/purchase/payment-success'
    | '/search/result'
    | '/setting/change-mail'
    | '/setting/change-password'
    | '/setting/notificationSetting'
    | '/setting/register-mail'
    | '/incoming/$callType/$userId'
    | '/outgoing/$callType/$userId'
    | '/profile/channel/$partnerId'
    | '/profile/detail/$partnerId'
    | '/profile/live-broadcaster/$partnerId'
    | '/profile/unbroadcaster/$partnerId'
    | '/profile/video-call-broadcaster/$partnerId'
    | '/fleamarket/item/$itemId'
    | '/fleamarket/purchase-confirmation/$itemId'
    | '/fleamarket/transaction/$transactionId'
    | '/mission/onboarding/add-line-friend'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_content'
    | '/_main'
    | '/about'
    | '/column'
    | '/health'
    | '/lp'
    | '/reauth'
    | '/_auth/confirm-mail'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/phone-verification'
    | '/_auth/reset-password'
    | '/_auth/signup'
    | '/_content/approach'
    | '/_content/commerce'
    | '/_content/faq'
    | '/_content/news'
    | '/_content/privacy'
    | '/_content/sitemap'
    | '/_content/tos'
    | '/_content/tuto'
    | '/_main/block'
    | '/_main/board'
    | '/_main/bookmark-list'
    | '/_main/callhistory-list'
    | '/_main/callrequest'
    | '/_main/conversation'
    | '/_main/daily-bonus'
    | '/_main/edit-profile'
    | '/_main/favorite-list'
    | '/_main/fleamarket'
    | '/_main/footprint-list'
    | '/_main/gallery'
    | '/_main/lovense'
    | '/_main/my-page'
    | '/_main/notification'
    | '/_main/onboarding'
    | '/_main/point-howto'
    | '/_main/premium-dailybonus'
    | '/_main/purchase'
    | '/_main/quickcharge'
    | '/_main/ranking'
    | '/_main/search'
    | '/_main/setting'
    | '/_main/video-list'
    | '/column/01_amateur'
    | '/column/02_jukujo'
    | '/column/03_tuma'
    | '/column/04_ol'
    | '/column/05_nurse'
    | '/column/06_cosplay'
    | '/column/07_idol'
    | '/column/08_gal'
    | '/column/09_loli'
    | '/column/10_megane'
    | '/column/11_sm'
    | '/column/12_fetish'
    | '/column/13_xxx'
    | '/line/callback'
    | '/lp/amateur'
    | '/lp/flea-market'
    | '/lp/free-points'
    | '/lp/jukujo'
    | '/lp/lovense-fullcontrol'
    | '/lp/promotion'
    | '/lp/review'
    | '/lp/transition'
    | '/message/$userId'
    | '/_content/faq/account'
    | '/_content/faq/beginner'
    | '/_content/faq/benefits'
    | '/_content/faq/connection'
    | '/_content/faq/fleamarket'
    | '/_content/faq/girls'
    | '/_content/faq/point'
    | '/_content/tuto/chat'
    | '/_content/tuto/videocall'
    | '/_content/tuto/videochat'
    | '/_main/fleamarket/$sellerId'
    | '/_main/fleamarket/todos'
    | '/_main/gallery/all'
    | '/_main/gallery/ranking'
    | '/_main/girls/all'
    | '/_main/girls/live-list'
    | '/_main/purchase/payment-success'
    | '/_main/search/result'
    | '/_main/setting/change-mail'
    | '/_main/setting/change-password'
    | '/_main/setting/notificationSetting'
    | '/_main/setting/register-mail'
    | '/incoming/$callType/$userId'
    | '/outgoing/$callType/$userId'
    | '/profile/channel/$partnerId'
    | '/profile/detail/$partnerId'
    | '/profile/live-broadcaster/$partnerId'
    | '/profile/unbroadcaster/$partnerId'
    | '/profile/video-call-broadcaster/$partnerId'
    | '/_main/fleamarket/item/$itemId'
    | '/_main/fleamarket/purchase-confirmation/$itemId'
    | '/_main/fleamarket/transaction/$transactionId'
    | '/_main/mission/onboarding/add-line-friend'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ContentRoute: typeof ContentRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
  AboutRoute: typeof AboutRoute
  ColumnRoute: typeof ColumnRouteWithChildren
  HealthRoute: typeof HealthRoute
  LpRoute: typeof LpRouteWithChildren
  ReauthRoute: typeof ReauthRoute
  LineCallbackRoute: typeof LineCallbackRoute
  MessageUserIdRoute: typeof MessageUserIdRoute
  IncomingCallTypeUserIdRoute: typeof IncomingCallTypeUserIdRoute
  OutgoingCallTypeUserIdRoute: typeof OutgoingCallTypeUserIdRoute
  ProfileChannelPartnerIdRoute: typeof ProfileChannelPartnerIdRoute
  ProfileDetailPartnerIdRoute: typeof ProfileDetailPartnerIdRoute
  ProfileLiveBroadcasterPartnerIdRoute: typeof ProfileLiveBroadcasterPartnerIdRoute
  ProfileUnbroadcasterPartnerIdRoute: typeof ProfileUnbroadcasterPartnerIdRoute
  ProfileVideoCallBroadcasterPartnerIdRoute: typeof ProfileVideoCallBroadcasterPartnerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reauth': {
      id: '/reauth'
      path: '/reauth'
      fullPath: '/reauth'
      preLoaderRoute: typeof ReauthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp': {
      id: '/lp'
      path: '/lp'
      fullPath: '/lp'
      preLoaderRoute: typeof LpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/column': {
      id: '/column'
      path: '/column'
      fullPath: '/column'
      preLoaderRoute: typeof ColumnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_content': {
      id: '/_content'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/message/$userId': {
      id: '/message/$userId'
      path: '/message/$userId'
      fullPath: '/message/$userId'
      preLoaderRoute: typeof MessageUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp/transition': {
      id: '/lp/transition'
      path: '/transition'
      fullPath: '/lp/transition'
      preLoaderRoute: typeof LpTransitionRouteImport
      parentRoute: typeof LpRoute
    }
    '/lp/review': {
      id: '/lp/review'
      path: '/review'
      fullPath: '/lp/review'
      preLoaderRoute: typeof LpReviewRouteImport
      parentRoute: typeof LpRoute
    }
    '/lp/promotion': {
      id: '/lp/promotion'
      path: '/promotion'
      fullPath: '/lp/promotion'
      preLoaderRoute: typeof LpPromotionRouteImport
      parentRoute: typeof LpRoute
    }
    '/lp/lovense-fullcontrol': {
      id: '/lp/lovense-fullcontrol'
      path: '/lovense-fullcontrol'
      fullPath: '/lp/lovense-fullcontrol'
      preLoaderRoute: typeof LpLovenseFullcontrolRouteImport
      parentRoute: typeof LpRoute
    }
    '/lp/jukujo': {
      id: '/lp/jukujo'
      path: '/jukujo'
      fullPath: '/lp/jukujo'
      preLoaderRoute: typeof LpJukujoRouteImport
      parentRoute: typeof LpRoute
    }
    '/lp/free-points': {
      id: '/lp/free-points'
      path: '/free-points'
      fullPath: '/lp/free-points'
      preLoaderRoute: typeof LpFreePointsRouteImport
      parentRoute: typeof LpRoute
    }
    '/lp/flea-market': {
      id: '/lp/flea-market'
      path: '/flea-market'
      fullPath: '/lp/flea-market'
      preLoaderRoute: typeof LpFleaMarketRouteImport
      parentRoute: typeof LpRoute
    }
    '/lp/amateur': {
      id: '/lp/amateur'
      path: '/amateur'
      fullPath: '/lp/amateur'
      preLoaderRoute: typeof LpAmateurRouteImport
      parentRoute: typeof LpRoute
    }
    '/line/callback': {
      id: '/line/callback'
      path: '/line/callback'
      fullPath: '/line/callback'
      preLoaderRoute: typeof LineCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/column/13_xxx': {
      id: '/column/13_xxx'
      path: '/13_xxx'
      fullPath: '/column/13_xxx'
      preLoaderRoute: typeof Column13_xxxRouteImport
      parentRoute: typeof ColumnRoute
    }
    '/column/12_fetish': {
      id: '/column/12_fetish'
      path: '/12_fetish'
      fullPath: '/column/12_fetish'
      preLoaderRoute: typeof Column12_fetishRouteImport
      parentRoute: typeof ColumnRoute
    }
    '/column/11_sm': {
      id: '/column/11_sm'
      path: '/11_sm'
      fullPath: '/column/11_sm'
      preLoaderRoute: typeof Column11_smRouteImport
      parentRoute: typeof ColumnRoute
    }
    '/column/10_megane': {
      id: '/column/10_megane'
      path: '/10_megane'
      fullPath: '/column/10_megane'
      preLoaderRoute: typeof Column10_meganeRouteImport
      parentRoute: typeof ColumnRoute
    }
    '/column/09_loli': {
      id: '/column/09_loli'
      path: '/09_loli'
      fullPath: '/column/09_loli'
      preLoaderRoute: typeof Column09_loliRouteImport
      parentRoute: typeof ColumnRoute
    }
    '/column/08_gal': {
      id: '/column/08_gal'
      path: '/08_gal'
      fullPath: '/column/08_gal'
      preLoaderRoute: typeof Column08_galRouteImport
      parentRoute: typeof ColumnRoute
    }
    '/column/07_idol': {
      id: '/column/07_idol'
      path: '/07_idol'
      fullPath: '/column/07_idol'
      preLoaderRoute: typeof Column07_idolRouteImport
      parentRoute: typeof ColumnRoute
    }
    '/column/06_cosplay': {
      id: '/column/06_cosplay'
      path: '/06_cosplay'
      fullPath: '/column/06_cosplay'
      preLoaderRoute: typeof Column06_cosplayRouteImport
      parentRoute: typeof ColumnRoute
    }
    '/column/05_nurse': {
      id: '/column/05_nurse'
      path: '/05_nurse'
      fullPath: '/column/05_nurse'
      preLoaderRoute: typeof Column05_nurseRouteImport
      parentRoute: typeof ColumnRoute
    }
    '/column/04_ol': {
      id: '/column/04_ol'
      path: '/04_ol'
      fullPath: '/column/04_ol'
      preLoaderRoute: typeof Column04_olRouteImport
      parentRoute: typeof ColumnRoute
    }
    '/column/03_tuma': {
      id: '/column/03_tuma'
      path: '/03_tuma'
      fullPath: '/column/03_tuma'
      preLoaderRoute: typeof Column03_tumaRouteImport
      parentRoute: typeof ColumnRoute
    }
    '/column/02_jukujo': {
      id: '/column/02_jukujo'
      path: '/02_jukujo'
      fullPath: '/column/02_jukujo'
      preLoaderRoute: typeof Column02_jukujoRouteImport
      parentRoute: typeof ColumnRoute
    }
    '/column/01_amateur': {
      id: '/column/01_amateur'
      path: '/01_amateur'
      fullPath: '/column/01_amateur'
      preLoaderRoute: typeof Column01_amateurRouteImport
      parentRoute: typeof ColumnRoute
    }
    '/_main/video-list': {
      id: '/_main/video-list'
      path: '/video-list'
      fullPath: '/video-list'
      preLoaderRoute: typeof MainVideoListRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/setting': {
      id: '/_main/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof MainSettingRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/search': {
      id: '/_main/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof MainSearchRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/ranking': {
      id: '/_main/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof MainRankingRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/quickcharge': {
      id: '/_main/quickcharge'
      path: '/quickcharge'
      fullPath: '/quickcharge'
      preLoaderRoute: typeof MainQuickchargeRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/purchase': {
      id: '/_main/purchase'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof MainPurchaseRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/premium-dailybonus': {
      id: '/_main/premium-dailybonus'
      path: '/premium-dailybonus'
      fullPath: '/premium-dailybonus'
      preLoaderRoute: typeof MainPremiumDailybonusRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/point-howto': {
      id: '/_main/point-howto'
      path: '/point-howto'
      fullPath: '/point-howto'
      preLoaderRoute: typeof MainPointHowtoRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/onboarding': {
      id: '/_main/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof MainOnboardingRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/notification': {
      id: '/_main/notification'
      path: '/notification'
      fullPath: '/notification'
      preLoaderRoute: typeof MainNotificationRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/my-page': {
      id: '/_main/my-page'
      path: '/my-page'
      fullPath: '/my-page'
      preLoaderRoute: typeof MainMyPageRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/lovense': {
      id: '/_main/lovense'
      path: '/lovense'
      fullPath: '/lovense'
      preLoaderRoute: typeof MainLovenseRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/gallery': {
      id: '/_main/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof MainGalleryRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/footprint-list': {
      id: '/_main/footprint-list'
      path: '/footprint-list'
      fullPath: '/footprint-list'
      preLoaderRoute: typeof MainFootprintListRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/fleamarket': {
      id: '/_main/fleamarket'
      path: '/fleamarket'
      fullPath: '/fleamarket'
      preLoaderRoute: typeof MainFleamarketRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/favorite-list': {
      id: '/_main/favorite-list'
      path: '/favorite-list'
      fullPath: '/favorite-list'
      preLoaderRoute: typeof MainFavoriteListRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/edit-profile': {
      id: '/_main/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof MainEditProfileRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/daily-bonus': {
      id: '/_main/daily-bonus'
      path: '/daily-bonus'
      fullPath: '/daily-bonus'
      preLoaderRoute: typeof MainDailyBonusRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/conversation': {
      id: '/_main/conversation'
      path: '/conversation'
      fullPath: '/conversation'
      preLoaderRoute: typeof MainConversationRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/callrequest': {
      id: '/_main/callrequest'
      path: '/callrequest'
      fullPath: '/callrequest'
      preLoaderRoute: typeof MainCallrequestRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/callhistory-list': {
      id: '/_main/callhistory-list'
      path: '/callhistory-list'
      fullPath: '/callhistory-list'
      preLoaderRoute: typeof MainCallhistoryListRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/bookmark-list': {
      id: '/_main/bookmark-list'
      path: '/bookmark-list'
      fullPath: '/bookmark-list'
      preLoaderRoute: typeof MainBookmarkListRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/board': {
      id: '/_main/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof MainBoardRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/block': {
      id: '/_main/block'
      path: '/block'
      fullPath: '/block'
      preLoaderRoute: typeof MainBlockRouteImport
      parentRoute: typeof MainRoute
    }
    '/_content/tuto': {
      id: '/_content/tuto'
      path: '/tuto'
      fullPath: '/tuto'
      preLoaderRoute: typeof ContentTutoRouteImport
      parentRoute: typeof ContentRoute
    }
    '/_content/tos': {
      id: '/_content/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof ContentTosRouteImport
      parentRoute: typeof ContentRoute
    }
    '/_content/sitemap': {
      id: '/_content/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof ContentSitemapRouteImport
      parentRoute: typeof ContentRoute
    }
    '/_content/privacy': {
      id: '/_content/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof ContentPrivacyRouteImport
      parentRoute: typeof ContentRoute
    }
    '/_content/news': {
      id: '/_content/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof ContentNewsRouteImport
      parentRoute: typeof ContentRoute
    }
    '/_content/faq': {
      id: '/_content/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof ContentFaqRouteImport
      parentRoute: typeof ContentRoute
    }
    '/_content/commerce': {
      id: '/_content/commerce'
      path: '/commerce'
      fullPath: '/commerce'
      preLoaderRoute: typeof ContentCommerceRouteImport
      parentRoute: typeof ContentRoute
    }
    '/_content/approach': {
      id: '/_content/approach'
      path: '/approach'
      fullPath: '/approach'
      preLoaderRoute: typeof ContentApproachRouteImport
      parentRoute: typeof ContentRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/phone-verification': {
      id: '/_auth/phone-verification'
      path: '/phone-verification'
      fullPath: '/phone-verification'
      preLoaderRoute: typeof AuthPhoneVerificationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/confirm-mail': {
      id: '/_auth/confirm-mail'
      path: '/confirm-mail'
      fullPath: '/confirm-mail'
      preLoaderRoute: typeof AuthConfirmMailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/profile/video-call-broadcaster/$partnerId': {
      id: '/profile/video-call-broadcaster/$partnerId'
      path: '/profile/video-call-broadcaster/$partnerId'
      fullPath: '/profile/video-call-broadcaster/$partnerId'
      preLoaderRoute: typeof ProfileVideoCallBroadcasterPartnerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/unbroadcaster/$partnerId': {
      id: '/profile/unbroadcaster/$partnerId'
      path: '/profile/unbroadcaster/$partnerId'
      fullPath: '/profile/unbroadcaster/$partnerId'
      preLoaderRoute: typeof ProfileUnbroadcasterPartnerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/live-broadcaster/$partnerId': {
      id: '/profile/live-broadcaster/$partnerId'
      path: '/profile/live-broadcaster/$partnerId'
      fullPath: '/profile/live-broadcaster/$partnerId'
      preLoaderRoute: typeof ProfileLiveBroadcasterPartnerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/detail/$partnerId': {
      id: '/profile/detail/$partnerId'
      path: '/profile/detail/$partnerId'
      fullPath: '/profile/detail/$partnerId'
      preLoaderRoute: typeof ProfileDetailPartnerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/channel/$partnerId': {
      id: '/profile/channel/$partnerId'
      path: '/profile/channel/$partnerId'
      fullPath: '/profile/channel/$partnerId'
      preLoaderRoute: typeof ProfileChannelPartnerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outgoing/$callType/$userId': {
      id: '/outgoing/$callType/$userId'
      path: '/outgoing/$callType/$userId'
      fullPath: '/outgoing/$callType/$userId'
      preLoaderRoute: typeof OutgoingCallTypeUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incoming/$callType/$userId': {
      id: '/incoming/$callType/$userId'
      path: '/incoming/$callType/$userId'
      fullPath: '/incoming/$callType/$userId'
      preLoaderRoute: typeof IncomingCallTypeUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/setting/register-mail': {
      id: '/_main/setting/register-mail'
      path: '/register-mail'
      fullPath: '/setting/register-mail'
      preLoaderRoute: typeof MainSettingRegisterMailRouteImport
      parentRoute: typeof MainSettingRoute
    }
    '/_main/setting/notificationSetting': {
      id: '/_main/setting/notificationSetting'
      path: '/notificationSetting'
      fullPath: '/setting/notificationSetting'
      preLoaderRoute: typeof MainSettingNotificationSettingRouteImport
      parentRoute: typeof MainSettingRoute
    }
    '/_main/setting/change-password': {
      id: '/_main/setting/change-password'
      path: '/change-password'
      fullPath: '/setting/change-password'
      preLoaderRoute: typeof MainSettingChangePasswordRouteImport
      parentRoute: typeof MainSettingRoute
    }
    '/_main/setting/change-mail': {
      id: '/_main/setting/change-mail'
      path: '/change-mail'
      fullPath: '/setting/change-mail'
      preLoaderRoute: typeof MainSettingChangeMailRouteImport
      parentRoute: typeof MainSettingRoute
    }
    '/_main/search/result': {
      id: '/_main/search/result'
      path: '/result'
      fullPath: '/search/result'
      preLoaderRoute: typeof MainSearchResultRouteImport
      parentRoute: typeof MainSearchRoute
    }
    '/_main/purchase/payment-success': {
      id: '/_main/purchase/payment-success'
      path: '/payment-success'
      fullPath: '/purchase/payment-success'
      preLoaderRoute: typeof MainPurchasePaymentSuccessRouteImport
      parentRoute: typeof MainPurchaseRoute
    }
    '/_main/girls/live-list': {
      id: '/_main/girls/live-list'
      path: '/girls/live-list'
      fullPath: '/girls/live-list'
      preLoaderRoute: typeof MainGirlsLiveListRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/girls/all': {
      id: '/_main/girls/all'
      path: '/girls/all'
      fullPath: '/girls/all'
      preLoaderRoute: typeof MainGirlsAllRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/gallery/ranking': {
      id: '/_main/gallery/ranking'
      path: '/ranking'
      fullPath: '/gallery/ranking'
      preLoaderRoute: typeof MainGalleryRankingRouteImport
      parentRoute: typeof MainGalleryRoute
    }
    '/_main/gallery/all': {
      id: '/_main/gallery/all'
      path: '/all'
      fullPath: '/gallery/all'
      preLoaderRoute: typeof MainGalleryAllRouteImport
      parentRoute: typeof MainGalleryRoute
    }
    '/_main/fleamarket/todos': {
      id: '/_main/fleamarket/todos'
      path: '/todos'
      fullPath: '/fleamarket/todos'
      preLoaderRoute: typeof MainFleamarketTodosRouteImport
      parentRoute: typeof MainFleamarketRoute
    }
    '/_main/fleamarket/$sellerId': {
      id: '/_main/fleamarket/$sellerId'
      path: '/$sellerId'
      fullPath: '/fleamarket/$sellerId'
      preLoaderRoute: typeof MainFleamarketSellerIdRouteImport
      parentRoute: typeof MainFleamarketRoute
    }
    '/_content/tuto/videochat': {
      id: '/_content/tuto/videochat'
      path: '/videochat'
      fullPath: '/tuto/videochat'
      preLoaderRoute: typeof ContentTutoVideochatRouteImport
      parentRoute: typeof ContentTutoRoute
    }
    '/_content/tuto/videocall': {
      id: '/_content/tuto/videocall'
      path: '/videocall'
      fullPath: '/tuto/videocall'
      preLoaderRoute: typeof ContentTutoVideocallRouteImport
      parentRoute: typeof ContentTutoRoute
    }
    '/_content/tuto/chat': {
      id: '/_content/tuto/chat'
      path: '/chat'
      fullPath: '/tuto/chat'
      preLoaderRoute: typeof ContentTutoChatRouteImport
      parentRoute: typeof ContentTutoRoute
    }
    '/_content/faq/point': {
      id: '/_content/faq/point'
      path: '/point'
      fullPath: '/faq/point'
      preLoaderRoute: typeof ContentFaqPointRouteImport
      parentRoute: typeof ContentFaqRoute
    }
    '/_content/faq/girls': {
      id: '/_content/faq/girls'
      path: '/girls'
      fullPath: '/faq/girls'
      preLoaderRoute: typeof ContentFaqGirlsRouteImport
      parentRoute: typeof ContentFaqRoute
    }
    '/_content/faq/fleamarket': {
      id: '/_content/faq/fleamarket'
      path: '/fleamarket'
      fullPath: '/faq/fleamarket'
      preLoaderRoute: typeof ContentFaqFleamarketRouteImport
      parentRoute: typeof ContentFaqRoute
    }
    '/_content/faq/connection': {
      id: '/_content/faq/connection'
      path: '/connection'
      fullPath: '/faq/connection'
      preLoaderRoute: typeof ContentFaqConnectionRouteImport
      parentRoute: typeof ContentFaqRoute
    }
    '/_content/faq/benefits': {
      id: '/_content/faq/benefits'
      path: '/benefits'
      fullPath: '/faq/benefits'
      preLoaderRoute: typeof ContentFaqBenefitsRouteImport
      parentRoute: typeof ContentFaqRoute
    }
    '/_content/faq/beginner': {
      id: '/_content/faq/beginner'
      path: '/beginner'
      fullPath: '/faq/beginner'
      preLoaderRoute: typeof ContentFaqBeginnerRouteImport
      parentRoute: typeof ContentFaqRoute
    }
    '/_content/faq/account': {
      id: '/_content/faq/account'
      path: '/account'
      fullPath: '/faq/account'
      preLoaderRoute: typeof ContentFaqAccountRouteImport
      parentRoute: typeof ContentFaqRoute
    }
    '/_main/mission/onboarding/add-line-friend': {
      id: '/_main/mission/onboarding/add-line-friend'
      path: '/mission/onboarding/add-line-friend'
      fullPath: '/mission/onboarding/add-line-friend'
      preLoaderRoute: typeof MainMissionOnboardingAddLineFriendRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/fleamarket/transaction/$transactionId': {
      id: '/_main/fleamarket/transaction/$transactionId'
      path: '/transaction/$transactionId'
      fullPath: '/fleamarket/transaction/$transactionId'
      preLoaderRoute: typeof MainFleamarketTransactionTransactionIdRouteImport
      parentRoute: typeof MainFleamarketRoute
    }
    '/_main/fleamarket/purchase-confirmation/$itemId': {
      id: '/_main/fleamarket/purchase-confirmation/$itemId'
      path: '/purchase-confirmation/$itemId'
      fullPath: '/fleamarket/purchase-confirmation/$itemId'
      preLoaderRoute: typeof MainFleamarketPurchaseConfirmationItemIdRouteImport
      parentRoute: typeof MainFleamarketRoute
    }
    '/_main/fleamarket/item/$itemId': {
      id: '/_main/fleamarket/item/$itemId'
      path: '/item/$itemId'
      fullPath: '/fleamarket/item/$itemId'
      preLoaderRoute: typeof MainFleamarketItemItemIdRouteImport
      parentRoute: typeof MainFleamarketRoute
    }
  }
}

interface AuthRouteChildren {
  AuthConfirmMailRoute: typeof AuthConfirmMailRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthPhoneVerificationRoute: typeof AuthPhoneVerificationRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthConfirmMailRoute: AuthConfirmMailRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthPhoneVerificationRoute: AuthPhoneVerificationRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ContentFaqRouteChildren {
  ContentFaqAccountRoute: typeof ContentFaqAccountRoute
  ContentFaqBeginnerRoute: typeof ContentFaqBeginnerRoute
  ContentFaqBenefitsRoute: typeof ContentFaqBenefitsRoute
  ContentFaqConnectionRoute: typeof ContentFaqConnectionRoute
  ContentFaqFleamarketRoute: typeof ContentFaqFleamarketRoute
  ContentFaqGirlsRoute: typeof ContentFaqGirlsRoute
  ContentFaqPointRoute: typeof ContentFaqPointRoute
}

const ContentFaqRouteChildren: ContentFaqRouteChildren = {
  ContentFaqAccountRoute: ContentFaqAccountRoute,
  ContentFaqBeginnerRoute: ContentFaqBeginnerRoute,
  ContentFaqBenefitsRoute: ContentFaqBenefitsRoute,
  ContentFaqConnectionRoute: ContentFaqConnectionRoute,
  ContentFaqFleamarketRoute: ContentFaqFleamarketRoute,
  ContentFaqGirlsRoute: ContentFaqGirlsRoute,
  ContentFaqPointRoute: ContentFaqPointRoute,
}

const ContentFaqRouteWithChildren = ContentFaqRoute._addFileChildren(
  ContentFaqRouteChildren,
)

interface ContentTutoRouteChildren {
  ContentTutoChatRoute: typeof ContentTutoChatRoute
  ContentTutoVideocallRoute: typeof ContentTutoVideocallRoute
  ContentTutoVideochatRoute: typeof ContentTutoVideochatRoute
}

const ContentTutoRouteChildren: ContentTutoRouteChildren = {
  ContentTutoChatRoute: ContentTutoChatRoute,
  ContentTutoVideocallRoute: ContentTutoVideocallRoute,
  ContentTutoVideochatRoute: ContentTutoVideochatRoute,
}

const ContentTutoRouteWithChildren = ContentTutoRoute._addFileChildren(
  ContentTutoRouteChildren,
)

interface ContentRouteChildren {
  ContentApproachRoute: typeof ContentApproachRoute
  ContentCommerceRoute: typeof ContentCommerceRoute
  ContentFaqRoute: typeof ContentFaqRouteWithChildren
  ContentNewsRoute: typeof ContentNewsRoute
  ContentPrivacyRoute: typeof ContentPrivacyRoute
  ContentSitemapRoute: typeof ContentSitemapRoute
  ContentTosRoute: typeof ContentTosRoute
  ContentTutoRoute: typeof ContentTutoRouteWithChildren
}

const ContentRouteChildren: ContentRouteChildren = {
  ContentApproachRoute: ContentApproachRoute,
  ContentCommerceRoute: ContentCommerceRoute,
  ContentFaqRoute: ContentFaqRouteWithChildren,
  ContentNewsRoute: ContentNewsRoute,
  ContentPrivacyRoute: ContentPrivacyRoute,
  ContentSitemapRoute: ContentSitemapRoute,
  ContentTosRoute: ContentTosRoute,
  ContentTutoRoute: ContentTutoRouteWithChildren,
}

const ContentRouteWithChildren =
  ContentRoute._addFileChildren(ContentRouteChildren)

interface MainFleamarketRouteChildren {
  MainFleamarketSellerIdRoute: typeof MainFleamarketSellerIdRoute
  MainFleamarketTodosRoute: typeof MainFleamarketTodosRoute
  MainFleamarketItemItemIdRoute: typeof MainFleamarketItemItemIdRoute
  MainFleamarketPurchaseConfirmationItemIdRoute: typeof MainFleamarketPurchaseConfirmationItemIdRoute
  MainFleamarketTransactionTransactionIdRoute: typeof MainFleamarketTransactionTransactionIdRoute
}

const MainFleamarketRouteChildren: MainFleamarketRouteChildren = {
  MainFleamarketSellerIdRoute: MainFleamarketSellerIdRoute,
  MainFleamarketTodosRoute: MainFleamarketTodosRoute,
  MainFleamarketItemItemIdRoute: MainFleamarketItemItemIdRoute,
  MainFleamarketPurchaseConfirmationItemIdRoute:
    MainFleamarketPurchaseConfirmationItemIdRoute,
  MainFleamarketTransactionTransactionIdRoute:
    MainFleamarketTransactionTransactionIdRoute,
}

const MainFleamarketRouteWithChildren = MainFleamarketRoute._addFileChildren(
  MainFleamarketRouteChildren,
)

interface MainGalleryRouteChildren {
  MainGalleryAllRoute: typeof MainGalleryAllRoute
  MainGalleryRankingRoute: typeof MainGalleryRankingRoute
}

const MainGalleryRouteChildren: MainGalleryRouteChildren = {
  MainGalleryAllRoute: MainGalleryAllRoute,
  MainGalleryRankingRoute: MainGalleryRankingRoute,
}

const MainGalleryRouteWithChildren = MainGalleryRoute._addFileChildren(
  MainGalleryRouteChildren,
)

interface MainPurchaseRouteChildren {
  MainPurchasePaymentSuccessRoute: typeof MainPurchasePaymentSuccessRoute
}

const MainPurchaseRouteChildren: MainPurchaseRouteChildren = {
  MainPurchasePaymentSuccessRoute: MainPurchasePaymentSuccessRoute,
}

const MainPurchaseRouteWithChildren = MainPurchaseRoute._addFileChildren(
  MainPurchaseRouteChildren,
)

interface MainSearchRouteChildren {
  MainSearchResultRoute: typeof MainSearchResultRoute
}

const MainSearchRouteChildren: MainSearchRouteChildren = {
  MainSearchResultRoute: MainSearchResultRoute,
}

const MainSearchRouteWithChildren = MainSearchRoute._addFileChildren(
  MainSearchRouteChildren,
)

interface MainSettingRouteChildren {
  MainSettingChangeMailRoute: typeof MainSettingChangeMailRoute
  MainSettingChangePasswordRoute: typeof MainSettingChangePasswordRoute
  MainSettingNotificationSettingRoute: typeof MainSettingNotificationSettingRoute
  MainSettingRegisterMailRoute: typeof MainSettingRegisterMailRoute
}

const MainSettingRouteChildren: MainSettingRouteChildren = {
  MainSettingChangeMailRoute: MainSettingChangeMailRoute,
  MainSettingChangePasswordRoute: MainSettingChangePasswordRoute,
  MainSettingNotificationSettingRoute: MainSettingNotificationSettingRoute,
  MainSettingRegisterMailRoute: MainSettingRegisterMailRoute,
}

const MainSettingRouteWithChildren = MainSettingRoute._addFileChildren(
  MainSettingRouteChildren,
)

interface MainRouteChildren {
  MainBlockRoute: typeof MainBlockRoute
  MainBoardRoute: typeof MainBoardRoute
  MainBookmarkListRoute: typeof MainBookmarkListRoute
  MainCallhistoryListRoute: typeof MainCallhistoryListRoute
  MainCallrequestRoute: typeof MainCallrequestRoute
  MainConversationRoute: typeof MainConversationRoute
  MainDailyBonusRoute: typeof MainDailyBonusRoute
  MainEditProfileRoute: typeof MainEditProfileRoute
  MainFavoriteListRoute: typeof MainFavoriteListRoute
  MainFleamarketRoute: typeof MainFleamarketRouteWithChildren
  MainFootprintListRoute: typeof MainFootprintListRoute
  MainGalleryRoute: typeof MainGalleryRouteWithChildren
  MainLovenseRoute: typeof MainLovenseRoute
  MainMyPageRoute: typeof MainMyPageRoute
  MainNotificationRoute: typeof MainNotificationRoute
  MainOnboardingRoute: typeof MainOnboardingRoute
  MainPointHowtoRoute: typeof MainPointHowtoRoute
  MainPremiumDailybonusRoute: typeof MainPremiumDailybonusRoute
  MainPurchaseRoute: typeof MainPurchaseRouteWithChildren
  MainQuickchargeRoute: typeof MainQuickchargeRoute
  MainRankingRoute: typeof MainRankingRoute
  MainSearchRoute: typeof MainSearchRouteWithChildren
  MainSettingRoute: typeof MainSettingRouteWithChildren
  MainVideoListRoute: typeof MainVideoListRoute
  MainGirlsAllRoute: typeof MainGirlsAllRoute
  MainGirlsLiveListRoute: typeof MainGirlsLiveListRoute
  MainMissionOnboardingAddLineFriendRoute: typeof MainMissionOnboardingAddLineFriendRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainBlockRoute: MainBlockRoute,
  MainBoardRoute: MainBoardRoute,
  MainBookmarkListRoute: MainBookmarkListRoute,
  MainCallhistoryListRoute: MainCallhistoryListRoute,
  MainCallrequestRoute: MainCallrequestRoute,
  MainConversationRoute: MainConversationRoute,
  MainDailyBonusRoute: MainDailyBonusRoute,
  MainEditProfileRoute: MainEditProfileRoute,
  MainFavoriteListRoute: MainFavoriteListRoute,
  MainFleamarketRoute: MainFleamarketRouteWithChildren,
  MainFootprintListRoute: MainFootprintListRoute,
  MainGalleryRoute: MainGalleryRouteWithChildren,
  MainLovenseRoute: MainLovenseRoute,
  MainMyPageRoute: MainMyPageRoute,
  MainNotificationRoute: MainNotificationRoute,
  MainOnboardingRoute: MainOnboardingRoute,
  MainPointHowtoRoute: MainPointHowtoRoute,
  MainPremiumDailybonusRoute: MainPremiumDailybonusRoute,
  MainPurchaseRoute: MainPurchaseRouteWithChildren,
  MainQuickchargeRoute: MainQuickchargeRoute,
  MainRankingRoute: MainRankingRoute,
  MainSearchRoute: MainSearchRouteWithChildren,
  MainSettingRoute: MainSettingRouteWithChildren,
  MainVideoListRoute: MainVideoListRoute,
  MainGirlsAllRoute: MainGirlsAllRoute,
  MainGirlsLiveListRoute: MainGirlsLiveListRoute,
  MainMissionOnboardingAddLineFriendRoute:
    MainMissionOnboardingAddLineFriendRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

interface ColumnRouteChildren {
  Column01_amateurRoute: typeof Column01_amateurRoute
  Column02_jukujoRoute: typeof Column02_jukujoRoute
  Column03_tumaRoute: typeof Column03_tumaRoute
  Column04_olRoute: typeof Column04_olRoute
  Column05_nurseRoute: typeof Column05_nurseRoute
  Column06_cosplayRoute: typeof Column06_cosplayRoute
  Column07_idolRoute: typeof Column07_idolRoute
  Column08_galRoute: typeof Column08_galRoute
  Column09_loliRoute: typeof Column09_loliRoute
  Column10_meganeRoute: typeof Column10_meganeRoute
  Column11_smRoute: typeof Column11_smRoute
  Column12_fetishRoute: typeof Column12_fetishRoute
  Column13_xxxRoute: typeof Column13_xxxRoute
}

const ColumnRouteChildren: ColumnRouteChildren = {
  Column01_amateurRoute: Column01_amateurRoute,
  Column02_jukujoRoute: Column02_jukujoRoute,
  Column03_tumaRoute: Column03_tumaRoute,
  Column04_olRoute: Column04_olRoute,
  Column05_nurseRoute: Column05_nurseRoute,
  Column06_cosplayRoute: Column06_cosplayRoute,
  Column07_idolRoute: Column07_idolRoute,
  Column08_galRoute: Column08_galRoute,
  Column09_loliRoute: Column09_loliRoute,
  Column10_meganeRoute: Column10_meganeRoute,
  Column11_smRoute: Column11_smRoute,
  Column12_fetishRoute: Column12_fetishRoute,
  Column13_xxxRoute: Column13_xxxRoute,
}

const ColumnRouteWithChildren =
  ColumnRoute._addFileChildren(ColumnRouteChildren)

interface LpRouteChildren {
  LpAmateurRoute: typeof LpAmateurRoute
  LpFleaMarketRoute: typeof LpFleaMarketRoute
  LpFreePointsRoute: typeof LpFreePointsRoute
  LpJukujoRoute: typeof LpJukujoRoute
  LpLovenseFullcontrolRoute: typeof LpLovenseFullcontrolRoute
  LpPromotionRoute: typeof LpPromotionRoute
  LpReviewRoute: typeof LpReviewRoute
  LpTransitionRoute: typeof LpTransitionRoute
}

const LpRouteChildren: LpRouteChildren = {
  LpAmateurRoute: LpAmateurRoute,
  LpFleaMarketRoute: LpFleaMarketRoute,
  LpFreePointsRoute: LpFreePointsRoute,
  LpJukujoRoute: LpJukujoRoute,
  LpLovenseFullcontrolRoute: LpLovenseFullcontrolRoute,
  LpPromotionRoute: LpPromotionRoute,
  LpReviewRoute: LpReviewRoute,
  LpTransitionRoute: LpTransitionRoute,
}

const LpRouteWithChildren = LpRoute._addFileChildren(LpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ContentRoute: ContentRouteWithChildren,
  MainRoute: MainRouteWithChildren,
  AboutRoute: AboutRoute,
  ColumnRoute: ColumnRouteWithChildren,
  HealthRoute: HealthRoute,
  LpRoute: LpRouteWithChildren,
  ReauthRoute: ReauthRoute,
  LineCallbackRoute: LineCallbackRoute,
  MessageUserIdRoute: MessageUserIdRoute,
  IncomingCallTypeUserIdRoute: IncomingCallTypeUserIdRoute,
  OutgoingCallTypeUserIdRoute: OutgoingCallTypeUserIdRoute,
  ProfileChannelPartnerIdRoute: ProfileChannelPartnerIdRoute,
  ProfileDetailPartnerIdRoute: ProfileDetailPartnerIdRoute,
  ProfileLiveBroadcasterPartnerIdRoute: ProfileLiveBroadcasterPartnerIdRoute,
  ProfileUnbroadcasterPartnerIdRoute: ProfileUnbroadcasterPartnerIdRoute,
  ProfileVideoCallBroadcasterPartnerIdRoute:
    ProfileVideoCallBroadcasterPartnerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
