/**
 * GA4/Repro共通イベント名定義
 *
 * GA4とReproで同じイベント名を使用するため、ここで一元管理する
 * イベント名の変更時はこのファイルのみを修正すればよい
 */
export const EVENT_NAMES = {
  // アクション
  COMPLETE_BUY_IMAGE: 'COMPLETE_BUY_IMAGE',
  COMPLETE_BUY_VIDEO: 'COMPLETE_BUY_VIDEO',
  COMPLETE_BUY_AUDIO: 'COMPLETE_BUY_AUDIO',
  COMPLETE_SEND_MESSAGE: 'COMPLETE_SEND_MESSAGE',
  COMPLETE_SEND_ONE_TAP_MESSAGE_FROM_BOARD:
    'COMPLETE_SEND_ONE_TAP_MESSAGE_FROM_BOARD',
  COMPLETE_SEND_FREE_MESSAGE_FROM_BOARD:
    'COMPLETE_SEND_FREE_MESSAGE_FROM_BOARD',
  COMPLETE_SEND_BOARD_MESSAGE: 'COMPLETE_SEND_BOARD_MESSAGE',
  COMPLETE_SEND_GIFT: 'COMPLETE_SEND_GIFT',
  COMPLETE_SEND_STAMP: 'COMPLETE_SEND_STAMP',
  ADD_FAVORITE: 'ADD_FAVORITE',
  REMOVE_FAVORITE: 'REMOVE_FAVORITE',
  SEND_GOOD: 'SEND_GOOD',
  TAP_OUTGOING_TO_VIDEO_LIST: 'TAP_OUTGOING_TO_VIDEO_LIST',
  TAP_JOIN_VIDEO_CHAT_FROM_BOOKMARK_MODAL:
    'TAP_JOIN_VIDEO_CHAT_FROM_BOOKMARK_MODAL',

  // 通話開始(ポイント消費開始)
  START_VIDEO_CALL: 'START_VIDEO_CALL',
  START_VOICE_CALL: 'START_VOICE_CALL',
  START_VIDEO_CHAT: 'START_VIDEO_CHAT',

  // 通話開始・終了イベント(詳細分析用)
  CALL_STARTED: 'CALL_STARTED',
  CALL_ENDED: 'CALL_ENDED',
  CALL_ATTEMPT_ENDED: 'CALL_ATTEMPT_ENDED',
  WATCH_VIDEO_CHAT_AS_FIRST_VIEWER: 'WATCH_VIDEO_CHAT_AS_FIRST_VIEWER',
  WATCH_VIDEO_CHAT_AS_VIEWER: 'WATCH_VIDEO_CHAT_AS_VIEWER',

  // 通話着信・発信・リクエスト
  INCOMING_VOICE_CALL: 'INCOMING_VOICE_CALL',
  INCOMING_VIDEO_CALL: 'INCOMING_VIDEO_CALL',
  OUTGOING_VOICE_CALL: 'OUTGOING_VOICE_CALL',
  OUTGOING_VIDEO_CALL: 'OUTGOING_VIDEO_CALL',
  SEND_VOICE_CALL_REQUEST: 'SEND_VOICE_CALL_REQUEST',
  SEND_VIDEO_CALL_REQUEST: 'SEND_VIDEO_CALL_REQUEST',

  // ビデオ通話・ビデオチャット内のアクション
  SEND_MESSAGE_IN_VIDEO_CHAT: 'SEND_MESSAGE_IN_VIDEO_CHAT',
  SEND_LOVENSE_IN_VIDEO_CHAT: 'SEND_LOVENSE_IN_VIDEO_CHAT',
  SEND_LOVENSE_IN_VIDEO_CALL: 'SEND_LOVENSE_IN_VIDEO_CALL',
  SEND_LOVENSE_FROM_QUICK_MENU: 'SEND_LOVENSE_FROM_QUICK_MENU',
  SEND_GIFT_IN_VIDEO_CHAT: 'SEND_GIFT_IN_VIDEO_CHAT',
  SEND_GIFT_IN_VIDEO_CALL: 'SEND_GIFT_IN_VIDEO_CALL',

  // ページ表示
  OPEN_GIRLS_ALL: 'OPEN_GIRLS_ALL',
  OPEN_CONVERSATION_ALL: 'OPEN_CONVERSATION_ALL',
  OPEN_BOARD: 'OPEN_BOARD',
  OPEN_GALLERY: 'OPEN_GALLERY',
  OPEN_MYPAGE: 'OPEN_MYPAGE',
  OPEN_FOOTPRINT_LIST: 'OPEN_FOOTPRINT_LIST',
  OPEN_FLEA_MARKET: 'OPEN_FLEA_MARKET',
  OPEN_PURCHASE: 'OPEN_PURCHASE',
  OPEN_SEARCH: 'OPEN_SEARCH',
  OPEN_VIDEO_LIST: 'OPEN_VIDEO_LIST',
  OPEN_DAILY_BONUS: 'OPEN_DAILY_BONUS',
  OPEN_PROFILE_DETAIL: 'OPEN_PROFILE_DETAIL',

  // キーイベント
  sign_up: 'sign_up',
  login: 'login',
  purchase: 'purchase',
  edit_profile: 'edit_profile',
  upload_profile_avatar: 'upload_profile_avatar',

  // その他
  START_FROM_PWA: 'START_FROM_PWA',
  SEARCH_FROM_BOARD: 'SEARCH_FROM_BOARD',

  // フリーマーケット関連
  OPEN_FLEA_MARKET_ITEM_DETAIL: 'OPEN_FLEA_MARKET_ITEM_DETAIL',
  TAP_PURCHASE_FLEA_MARKET_ITEM: 'TAP_PURCHASE_FLEA_MARKET_ITEM',
  COMPLETE_PURCHASE_FLEA_MARKET_ITEM: 'COMPLETE_PURCHASE_FLEA_MARKET_ITEM',
  SEND_GOOD_FLEA_MARKET_ITEM: 'SEND_GOOD_FLEA_MARKET_ITEM',

  // ポイント購入関連
  PURCHASE_SAME_CARD: 'PURCHASE_SAME_CARD',

  // ポイント購入ページ: コースクリック計測（動的に金額サフィックス付与）
  CLICK_POINT_COURSE: 'CLICK_POINT_COURSE',
  CLICK_BONUS_POINT_COURSE: 'CLICK_BONUS_POINT_COURSE',

  // 通知関連
  APPROVE_NOTIFICATION: 'Approve notification',
  SHOW_NOTIFICATION_PERMISSION: 'Show notification permission',

  // 削除予定
  COMPLETE_VIDEO_CHAT: 'Complete video chat',
  COMPLETE_VIDEO_CHAT_BY_STANDBY: 'Complete video chat by standby',
  COMPLETE_VIDEO_CHAT_BY_OUTGOING: 'Complete video chat by outgoing',
  COMPLETE_VIDEO_CHAT_BY_INCOMING: 'Complete video chat by incoming',
  COMPLETE_VOICE_CALL: 'Complete voice call',
  COMPLETE_VOICE_CALL_BY_INCOMING: 'Complete voice call by incoming',
  COMPLETE_VIDEO_CALL: 'Complete video call',
  COMPLETE_VIDEO_CALL_BY_INCOMING: 'Complete video call by incoming',
  COMPLETE_SEND_VIDEO_FILE_REQUEST: 'Complete send video file request',
  COMPLETE_SEND_IMAGE_FILE_REQUEST: 'Complete send image file request',
  COMPLETE_SEND_SECRETMESSAGE: 'Complete send secret message',
  COMPLETE_SEND_PRESENTMENU: 'Complete send present menu',
  COMPLETE_SEND_PRESENTMENU_FOR_LABEL: 'Complete send present menu for lavel',
  COMPLETE_SEND_LOVENSE_LIVE: 'Complete send lovense live',
  COMPLETE_SEND_LOVENSE_VIDEO: 'Complete send lovense video',
  COMPLETE_SEND_LOVENSE: 'Complete send lovense',
  COMPLETE_ONE_TAP_FAVORITE: 'Complete one tap favorite',
  TAP_MESSAGE_BOARD: 'Tap message board',
  TAP_VIDEOCALL_BOARD: 'Tap videochat board',
  TAP_VOICECALL_BOARD: 'Tap voicecall board',
  TAP_JOIN_BOARD: 'Tap join board',
  COMPLETE_SEARCH_USER: 'Complete search user',
  TAP_VIDEOCALL_RANKING: 'Tap videochat ranking',
  TAP_VOICECALL_RANKING: 'Tap voicecall ranking',
  TAP_DUMMY_MESSAGE: 'Tap dummy message',
  COMPLETE_PURCHASE_VIDEO_GALLERY: 'Complete purchase video gallery',
  COMPLETE_PURCHASE_IMAGE_GALLERY: 'Complete purchase image gallery',
  TAP_ADD_BOOKMARK: 'Tap add bookmark',
  TAP_FAVORITE: 'Tap favorite',
  TAP_JOIN_RANKING: 'Tap join ranking',
  COMPLETE_SEND_IMAGE: 'Complete send image',
  GET_NOTIFICATION_BONUS: 'Get notification bonus',
  TAP_ADD_BLOCK: 'Tap add block',
  TAP_REMOVE_BLOCK: 'Tap remove block',
  COMPLETE_ADD_REPORT: 'Tap add report',
  COMPLETE_TIMELINE_COMMENT: 'Complete timeline comment',
  COMPLETE_TIMELINE_LIKE: 'Complete timeline like',
  COMPLETE_TIMELINE_POST: 'Complete timeline post',
  TAP_REGISTER_BANNER_ON_PROFILE: 'Tap register banner on profile',
  TAP_LOVENSE_ROULETTE_BUTTON: 'Tap lovense roulette button',

  // ライブ配信録画プレビュー関連
  TAP_PREVIEW_WATCH_BUTTON: 'TAP_PREVIEW_WATCH_BUTTON',
  TAP_PREVIEW_JOIN_BUTTON: 'TAP_PREVIEW_JOIN_BUTTON',

  // ホーム画面からのビデオ通話確認モーダル
  TAP_VIDEO_CALL_CONFIRM_START: 'TAP_VIDEO_CALL_CONFIRM_START',

  // レビュー関連
  TAP_RECOMMENDATION_BUTTON: 'TAP_RECOMMENDATION_BUTTON',
  COMPLETE_SUBMIT_REVIEW: 'COMPLETE_SUBMIT_REVIEW',

  // オンボーディングクレカ登録バナー
  TAP_ONBOARDING_CREDIT_BANNER: 'TAP_ONBOARDING_CREDIT_BANNER',
} as const;

export type EventName = (typeof EVENT_NAMES)[keyof typeof EVENT_NAMES];
