import { ADJUST_TOKENS } from './adjustTokens';
import { EVENT_NAMES } from './eventNames';
import { EventProvider, type EventTokenConfig } from './eventProviders';

/**
 * GA4に送信するイベントを管理している
 * 各イベントはGA4、Repro、Adjustのトークンを一元管理
 *
 * - イベント名: eventNames.ts で管理
 * - Adjustトークン: adjustTokens.ts で管理
 */
export const event = {
  // アクション
  COMPLETE_BUY_IMAGE: {
    [EventProvider.GA4]: EVENT_NAMES.COMPLETE_BUY_IMAGE,
    [EventProvider.Repro]: EVENT_NAMES.COMPLETE_BUY_IMAGE,
    [EventProvider.Adjust]: ADJUST_TOKENS.COMPLETE_BUY_IMAGE,
  },
  COMPLETE_BUY_VIDEO: {
    [EventProvider.GA4]: EVENT_NAMES.COMPLETE_BUY_VIDEO,
    [EventProvider.Repro]: EVENT_NAMES.COMPLETE_BUY_VIDEO,
    [EventProvider.Adjust]: ADJUST_TOKENS.COMPLETE_BUY_VIDEO,
  },
  COMPLETE_BUY_AUDIO: {
    [EventProvider.GA4]: EVENT_NAMES.COMPLETE_BUY_AUDIO,
    [EventProvider.Repro]: EVENT_NAMES.COMPLETE_BUY_AUDIO,
    // Adjustトークンは未定義
  },
  COMPLETE_SEND_MESSAGE: {
    [EventProvider.GA4]: EVENT_NAMES.COMPLETE_SEND_MESSAGE,
    [EventProvider.Repro]: EVENT_NAMES.COMPLETE_SEND_MESSAGE,
    [EventProvider.Adjust]: ADJUST_TOKENS.COMPLETE_SEND_MESSAGE,
  },
  // 掲示板への投稿完了（1-Tap投稿または任意メッセージ投稿）
  // COMPLETE_SEND_BOARD_MESSAGE: {
  //   [EventProvider.GA4]: EVENT_NAMES.COMPLETE_SEND_BOARD_MESSAGE,
  //   [EventProvider.Repro]: EVENT_NAMES.COMPLETE_SEND_BOARD_MESSAGE,
  //   [EventProvider.Adjust]: ADJUST_TOKENS.COMPLETE_SEND_BOARD_MESSAGE,
  // },
  // 掲示板1-Tap投稿完了イベント
  COMPLETE_SEND_ONE_TAP_MESSAGE_FROM_BOARD: {
    [EventProvider.GA4]: EVENT_NAMES.COMPLETE_SEND_ONE_TAP_MESSAGE_FROM_BOARD,
    [EventProvider.Repro]: EVENT_NAMES.COMPLETE_SEND_ONE_TAP_MESSAGE_FROM_BOARD,
  },
  // 掲示板自由投稿完了イベント
  COMPLETE_SEND_FREE_MESSAGE_FROM_BOARD: {
    [EventProvider.GA4]: EVENT_NAMES.COMPLETE_SEND_FREE_MESSAGE_FROM_BOARD,
    [EventProvider.Repro]: EVENT_NAMES.COMPLETE_SEND_FREE_MESSAGE_FROM_BOARD,
  },
  // メッセージ詳細画面からギフト送信
  COMPLETE_SEND_GIFT: {
    [EventProvider.GA4]: EVENT_NAMES.COMPLETE_SEND_GIFT,
    [EventProvider.Repro]: EVENT_NAMES.COMPLETE_SEND_GIFT,
  },
  COMPLETE_SEND_STAMP: {
    [EventProvider.GA4]: EVENT_NAMES.COMPLETE_SEND_STAMP,
    [EventProvider.Repro]: EVENT_NAMES.COMPLETE_SEND_STAMP,
  },
  ADD_FAVORITE: {
    [EventProvider.GA4]: EVENT_NAMES.ADD_FAVORITE,
    [EventProvider.Repro]: EVENT_NAMES.ADD_FAVORITE,
  },
  REMOVE_FAVORITE: {
    [EventProvider.GA4]: EVENT_NAMES.REMOVE_FAVORITE,
    [EventProvider.Repro]: EVENT_NAMES.REMOVE_FAVORITE,
  },
  SEND_GOOD: {
    [EventProvider.GA4]: EVENT_NAMES.SEND_GOOD,
    [EventProvider.Repro]: EVENT_NAMES.SEND_GOOD,
    [EventProvider.Adjust]: ADJUST_TOKENS.SEND_GOOD,
  },
  // /video-listから発信
  TAP_OUTGOING_TO_VIDEO_LIST: {
    [EventProvider.GA4]: EVENT_NAMES.TAP_OUTGOING_TO_VIDEO_LIST,
    [EventProvider.Repro]: EVENT_NAMES.TAP_OUTGOING_TO_VIDEO_LIST,
  },
  // 通話開始(ポイント消費開始)
  START_VIDEO_CALL: {
    [EventProvider.GA4]: EVENT_NAMES.START_VIDEO_CALL,
    [EventProvider.Repro]: EVENT_NAMES.START_VIDEO_CALL,
    [EventProvider.Adjust]: ADJUST_TOKENS.START_VIDEO_CALL,
  },
  START_VOICE_CALL: {
    [EventProvider.GA4]: EVENT_NAMES.START_VOICE_CALL,
    [EventProvider.Repro]: EVENT_NAMES.START_VOICE_CALL,
    [EventProvider.Adjust]: ADJUST_TOKENS.START_VOICE_CALL,
  },
  START_VIDEO_CHAT: {
    [EventProvider.GA4]: EVENT_NAMES.START_VIDEO_CHAT,
    [EventProvider.Repro]: EVENT_NAMES.START_VIDEO_CHAT,
    [EventProvider.Adjust]: ADJUST_TOKENS.START_VIDEO_CHAT,
  },
  // 通話開始・終了イベント(詳細分析用)
  CALL_STARTED: {
    [EventProvider.GA4]: EVENT_NAMES.CALL_STARTED,
    [EventProvider.Repro]: EVENT_NAMES.CALL_STARTED,
  },
  CALL_ENDED: {
    [EventProvider.GA4]: EVENT_NAMES.CALL_ENDED,
    [EventProvider.Repro]: EVENT_NAMES.CALL_ENDED,
  },
  // 通話試行の終了（未成立: 拒否/無応答など）
  CALL_ATTEMPT_ENDED: {
    [EventProvider.GA4]: EVENT_NAMES.CALL_ATTEMPT_ENDED,
    [EventProvider.Repro]: EVENT_NAMES.CALL_ATTEMPT_ENDED,
  },
  WATCH_VIDEO_CHAT_AS_FIRST_VIEWER: {
    [EventProvider.GA4]: EVENT_NAMES.WATCH_VIDEO_CHAT_AS_FIRST_VIEWER,
    [EventProvider.Repro]: EVENT_NAMES.WATCH_VIDEO_CHAT_AS_FIRST_VIEWER,
  },
  WATCH_VIDEO_CHAT_AS_VIEWER: {
    [EventProvider.GA4]: EVENT_NAMES.WATCH_VIDEO_CHAT_AS_VIEWER,
    [EventProvider.Repro]: EVENT_NAMES.WATCH_VIDEO_CHAT_AS_VIEWER,
  },
  // ブックマークモーダルからのビデオチャット入室
  TAP_JOIN_VIDEO_CHAT_FROM_BOOKMARK_MODAL: {
    [EventProvider.GA4]: EVENT_NAMES.TAP_JOIN_VIDEO_CHAT_FROM_BOOKMARK_MODAL,
    [EventProvider.Repro]: EVENT_NAMES.TAP_JOIN_VIDEO_CHAT_FROM_BOOKMARK_MODAL,
  },
  // 通話着信・発信・リクエスト
  INCOMING_VOICE_CALL: {
    [EventProvider.GA4]: EVENT_NAMES.INCOMING_VOICE_CALL,
    [EventProvider.Repro]: EVENT_NAMES.INCOMING_VOICE_CALL,
  },
  INCOMING_VIDEO_CALL: {
    [EventProvider.GA4]: EVENT_NAMES.INCOMING_VIDEO_CALL,
    [EventProvider.Repro]: EVENT_NAMES.INCOMING_VIDEO_CALL,
  },
  OUTGOING_VOICE_CALL: {
    [EventProvider.GA4]: EVENT_NAMES.OUTGOING_VOICE_CALL,
    [EventProvider.Repro]: EVENT_NAMES.OUTGOING_VOICE_CALL,
  },
  OUTGOING_VIDEO_CALL: {
    [EventProvider.GA4]: EVENT_NAMES.OUTGOING_VIDEO_CALL,
    [EventProvider.Repro]: EVENT_NAMES.OUTGOING_VIDEO_CALL,
  },
  SEND_VOICE_CALL_REQUEST: {
    [EventProvider.GA4]: EVENT_NAMES.SEND_VOICE_CALL_REQUEST,
    [EventProvider.Repro]: EVENT_NAMES.SEND_VOICE_CALL_REQUEST,
  },
  SEND_VIDEO_CALL_REQUEST: {
    [EventProvider.GA4]: EVENT_NAMES.SEND_VIDEO_CALL_REQUEST,
    [EventProvider.Repro]: EVENT_NAMES.SEND_VIDEO_CALL_REQUEST,
  },
  // ビデオ通話・ビデオチャット内のアクション
  SEND_MESSAGE_IN_VIDEO_CHAT: {
    [EventProvider.GA4]: EVENT_NAMES.SEND_MESSAGE_IN_VIDEO_CHAT,
    [EventProvider.Repro]: EVENT_NAMES.SEND_MESSAGE_IN_VIDEO_CHAT,
  },
  SEND_LOVENSE_IN_VIDEO_CHAT: {
    [EventProvider.GA4]: EVENT_NAMES.SEND_LOVENSE_IN_VIDEO_CHAT,
    [EventProvider.Repro]: EVENT_NAMES.SEND_LOVENSE_IN_VIDEO_CHAT,
  },
  SEND_LOVENSE_IN_VIDEO_CALL: {
    [EventProvider.GA4]: EVENT_NAMES.SEND_LOVENSE_IN_VIDEO_CALL,
    [EventProvider.Repro]: EVENT_NAMES.SEND_LOVENSE_IN_VIDEO_CALL,
  },
  // LovenseQuickMenuからのワンタップ送信
  SEND_LOVENSE_FROM_QUICK_MENU: {
    [EventProvider.GA4]: EVENT_NAMES.SEND_LOVENSE_FROM_QUICK_MENU,
    [EventProvider.Repro]: EVENT_NAMES.SEND_LOVENSE_FROM_QUICK_MENU,
  },
  SEND_GIFT_IN_VIDEO_CHAT: {
    [EventProvider.GA4]: EVENT_NAMES.SEND_GIFT_IN_VIDEO_CHAT,
    [EventProvider.Repro]: EVENT_NAMES.SEND_GIFT_IN_VIDEO_CHAT,
  },
  SEND_GIFT_IN_VIDEO_CALL: {
    [EventProvider.GA4]: EVENT_NAMES.SEND_GIFT_IN_VIDEO_CALL,
    [EventProvider.Repro]: EVENT_NAMES.SEND_GIFT_IN_VIDEO_CALL,
  },
  // ページ表示
  OPEN_GIRLS_ALL: {
    [EventProvider.GA4]: EVENT_NAMES.OPEN_GIRLS_ALL,
    [EventProvider.Repro]: EVENT_NAMES.OPEN_GIRLS_ALL,
  },
  OPEN_CONVERSATION_ALL: {
    [EventProvider.GA4]: EVENT_NAMES.OPEN_CONVERSATION_ALL,
    [EventProvider.Repro]: EVENT_NAMES.OPEN_CONVERSATION_ALL,
  },
  OPEN_BOARD: {
    [EventProvider.GA4]: EVENT_NAMES.OPEN_BOARD,
    [EventProvider.Repro]: EVENT_NAMES.OPEN_BOARD,
  },
  OPEN_GALLERY: {
    [EventProvider.GA4]: EVENT_NAMES.OPEN_GALLERY,
    [EventProvider.Repro]: EVENT_NAMES.OPEN_GALLERY,
  },
  OPEN_MYPAGE: {
    [EventProvider.GA4]: EVENT_NAMES.OPEN_MYPAGE,
    [EventProvider.Repro]: EVENT_NAMES.OPEN_MYPAGE,
  },
  OPEN_FOOTPRINT_LIST: {
    [EventProvider.GA4]: EVENT_NAMES.OPEN_FOOTPRINT_LIST,
    [EventProvider.Repro]: EVENT_NAMES.OPEN_FOOTPRINT_LIST,
  },
  OPEN_FLEA_MARKET: {
    [EventProvider.GA4]: EVENT_NAMES.OPEN_FLEA_MARKET,
    [EventProvider.Repro]: EVENT_NAMES.OPEN_FLEA_MARKET,
  },
  OPEN_PURCHASE: {
    [EventProvider.GA4]: EVENT_NAMES.OPEN_PURCHASE,
    [EventProvider.Repro]: EVENT_NAMES.OPEN_PURCHASE,
  },
  OPEN_SEARCH: {
    [EventProvider.GA4]: EVENT_NAMES.OPEN_SEARCH,
    [EventProvider.Repro]: EVENT_NAMES.OPEN_SEARCH,
  },
  OPEN_VIDEO_LIST: {
    [EventProvider.GA4]: EVENT_NAMES.OPEN_VIDEO_LIST,
    [EventProvider.Repro]: EVENT_NAMES.OPEN_VIDEO_LIST,
  },
  OPEN_DAILY_BONUS: {
    [EventProvider.GA4]: EVENT_NAMES.OPEN_DAILY_BONUS,
    [EventProvider.Repro]: EVENT_NAMES.OPEN_DAILY_BONUS,
  },
  OPEN_PROFILE_DETAIL: {
    [EventProvider.GA4]: EVENT_NAMES.OPEN_PROFILE_DETAIL,
    [EventProvider.Repro]: EVENT_NAMES.OPEN_PROFILE_DETAIL,
  },
  // キーイベント
  sign_up: {
    [EventProvider.GA4]: EVENT_NAMES.sign_up,
    [EventProvider.Repro]: EVENT_NAMES.sign_up,
    [EventProvider.Adjust]: ADJUST_TOKENS.sign_up,
  },
  login: {
    [EventProvider.GA4]: EVENT_NAMES.login,
    [EventProvider.Repro]: EVENT_NAMES.login,
  },
  purchase: {
    [EventProvider.GA4]: EVENT_NAMES.purchase,
    [EventProvider.Repro]: EVENT_NAMES.purchase,
  },
  edit_profile: {
    [EventProvider.GA4]: EVENT_NAMES.edit_profile,
    [EventProvider.Repro]: EVENT_NAMES.edit_profile,
    [EventProvider.Adjust]: ADJUST_TOKENS.edit_profile,
  },
  upload_profile_avatar: {
    [EventProvider.GA4]: EVENT_NAMES.upload_profile_avatar,
    [EventProvider.Repro]: EVENT_NAMES.upload_profile_avatar,
  },
  // その他
  START_FROM_PWA: {
    [EventProvider.GA4]: EVENT_NAMES.START_FROM_PWA,
    [EventProvider.Repro]: EVENT_NAMES.START_FROM_PWA,
  },

  // 掲示板検索
  SEARCH_FROM_BOARD: {
    [EventProvider.GA4]: EVENT_NAMES.SEARCH_FROM_BOARD,
    [EventProvider.Repro]: EVENT_NAMES.SEARCH_FROM_BOARD,
  },

  // フリーマーケット関連
  OPEN_FLEA_MARKET_ITEM_DETAIL: {
    [EventProvider.GA4]: EVENT_NAMES.OPEN_FLEA_MARKET_ITEM_DETAIL,
    [EventProvider.Repro]: EVENT_NAMES.OPEN_FLEA_MARKET_ITEM_DETAIL,
  },
  TAP_PURCHASE_FLEA_MARKET_ITEM: {
    [EventProvider.GA4]: EVENT_NAMES.TAP_PURCHASE_FLEA_MARKET_ITEM,
    [EventProvider.Repro]: EVENT_NAMES.TAP_PURCHASE_FLEA_MARKET_ITEM,
  },
  COMPLETE_PURCHASE_FLEA_MARKET_ITEM: {
    [EventProvider.GA4]: EVENT_NAMES.COMPLETE_PURCHASE_FLEA_MARKET_ITEM,
    [EventProvider.Repro]: EVENT_NAMES.COMPLETE_PURCHASE_FLEA_MARKET_ITEM,
  },
  SEND_GOOD_FLEA_MARKET_ITEM: {
    [EventProvider.GA4]: EVENT_NAMES.SEND_GOOD_FLEA_MARKET_ITEM,
    [EventProvider.Repro]: EVENT_NAMES.SEND_GOOD_FLEA_MARKET_ITEM,
  },

  // ポイント購入関連
  PURCHASE_SAME_CARD: {
    [EventProvider.GA4]: EVENT_NAMES.PURCHASE_SAME_CARD,
    [EventProvider.Repro]: EVENT_NAMES.PURCHASE_SAME_CARD,
  },

  // その他
  APPROVE_NOTIFICATION: {
    [EventProvider.GA4]: EVENT_NAMES.APPROVE_NOTIFICATION,
    [EventProvider.Repro]: EVENT_NAMES.APPROVE_NOTIFICATION,
  },
  SHOW_NOTIFICATION_PERMISSION: {
    [EventProvider.GA4]: EVENT_NAMES.SHOW_NOTIFICATION_PERMISSION,
    [EventProvider.Repro]: EVENT_NAMES.SHOW_NOTIFICATION_PERMISSION,
  },

  //削除予定
  COMPLETE_VIDEO_CHAT: {
    [EventProvider.GA4]: EVENT_NAMES.COMPLETE_VIDEO_CHAT,
    [EventProvider.Repro]: EVENT_NAMES.COMPLETE_VIDEO_CHAT,
  },
  COMPLETE_VIDEO_CHAT_BY_STANDBY: {
    [EventProvider.GA4]: EVENT_NAMES.COMPLETE_VIDEO_CHAT_BY_STANDBY,
    [EventProvider.Repro]: EVENT_NAMES.COMPLETE_VIDEO_CHAT_BY_STANDBY,
  },
  COMPLETE_VIDEO_CHAT_BY_OUTGOING: {
    [EventProvider.GA4]: EVENT_NAMES.COMPLETE_VIDEO_CHAT_BY_OUTGOING,
    [EventProvider.Repro]: EVENT_NAMES.COMPLETE_VIDEO_CHAT_BY_OUTGOING,
  },
  COMPLETE_VIDEO_CHAT_BY_INCOMING: {
    [EventProvider.GA4]: EVENT_NAMES.COMPLETE_VIDEO_CHAT_BY_INCOMING,
    [EventProvider.Repro]: EVENT_NAMES.COMPLETE_VIDEO_CHAT_BY_INCOMING,
  },
  COMPLETE_VOICE_CALL: {
    [EventProvider.GA4]: EVENT_NAMES.COMPLETE_VOICE_CALL,
    [EventProvider.Repro]: EVENT_NAMES.COMPLETE_VOICE_CALL,
  },
  COMPLETE_VOICE_CALL_BY_INCOMING: {
    [EventProvider.GA4]: EVENT_NAMES.COMPLETE_VOICE_CALL_BY_INCOMING,
    [EventProvider.Repro]: EVENT_NAMES.COMPLETE_VOICE_CALL_BY_INCOMING,
  },
  COMPLETE_VIDEO_CALL: {
    [EventProvider.GA4]: EVENT_NAMES.COMPLETE_VIDEO_CALL,
    [EventProvider.Repro]: EVENT_NAMES.COMPLETE_VIDEO_CALL,
  },
  COMPLETE_VIDEO_CALL_BY_INCOMING: {
    [EventProvider.GA4]: EVENT_NAMES.COMPLETE_VIDEO_CALL_BY_INCOMING,
    [EventProvider.Repro]: EVENT_NAMES.COMPLETE_VIDEO_CALL_BY_INCOMING,
  },
  COMPLETE_SEND_VIDEO_FILE_REQUEST: {
    [EventProvider.GA4]: EVENT_NAMES.COMPLETE_SEND_VIDEO_FILE_REQUEST,
    [EventProvider.Repro]: EVENT_NAMES.COMPLETE_SEND_VIDEO_FILE_REQUEST,
  },
  COMPLETE_SEND_IMAGE_FILE_REQUEST: {
    [EventProvider.GA4]: EVENT_NAMES.COMPLETE_SEND_IMAGE_FILE_REQUEST,
    [EventProvider.Repro]: EVENT_NAMES.COMPLETE_SEND_IMAGE_FILE_REQUEST,
  },
  COMPLETE_SEND_SECRETMESSAGE: {
    [EventProvider.GA4]: EVENT_NAMES.COMPLETE_SEND_SECRETMESSAGE,
    [EventProvider.Repro]: EVENT_NAMES.COMPLETE_SEND_SECRETMESSAGE,
  },
  COMPLETE_SEND_PRESENTMENU: {
    [EventProvider.GA4]: EVENT_NAMES.COMPLETE_SEND_PRESENTMENU,
    [EventProvider.Repro]: EVENT_NAMES.COMPLETE_SEND_PRESENTMENU,
  },
  COMPLETE_SEND_PRESENTMENU_FOR_LABEL: {
    [EventProvider.GA4]: EVENT_NAMES.COMPLETE_SEND_PRESENTMENU_FOR_LABEL,
    [EventProvider.Repro]: EVENT_NAMES.COMPLETE_SEND_PRESENTMENU_FOR_LABEL,
  },
  COMPLETE_SEND_LOVENSE_LIVE: {
    [EventProvider.GA4]: EVENT_NAMES.COMPLETE_SEND_LOVENSE_LIVE,
    [EventProvider.Repro]: EVENT_NAMES.COMPLETE_SEND_LOVENSE_LIVE,
  },
  COMPLETE_SEND_LOVENSE_VIDEO: {
    [EventProvider.GA4]: EVENT_NAMES.COMPLETE_SEND_LOVENSE_VIDEO,
    [EventProvider.Repro]: EVENT_NAMES.COMPLETE_SEND_LOVENSE_VIDEO,
  },
  COMPLETE_SEND_LOVENSE: {
    [EventProvider.GA4]: EVENT_NAMES.COMPLETE_SEND_LOVENSE,
    [EventProvider.Repro]: EVENT_NAMES.COMPLETE_SEND_LOVENSE,
  },
  COMPLETE_ONE_TAP_FAVORITE: {
    [EventProvider.GA4]: EVENT_NAMES.COMPLETE_ONE_TAP_FAVORITE,
    [EventProvider.Repro]: EVENT_NAMES.COMPLETE_ONE_TAP_FAVORITE,
  },
  TAP_MESSAGE_BOARD: {
    [EventProvider.GA4]: EVENT_NAMES.TAP_MESSAGE_BOARD,
    [EventProvider.Repro]: EVENT_NAMES.TAP_MESSAGE_BOARD,
  },
  TAP_VIDEOCALL_BOARD: {
    [EventProvider.GA4]: EVENT_NAMES.TAP_VIDEOCALL_BOARD,
    [EventProvider.Repro]: EVENT_NAMES.TAP_VIDEOCALL_BOARD,
  },
  TAP_VOICECALL_BOARD: {
    [EventProvider.GA4]: EVENT_NAMES.TAP_VOICECALL_BOARD,
    [EventProvider.Repro]: EVENT_NAMES.TAP_VOICECALL_BOARD,
  },
  TAP_JOIN_BOARD: {
    [EventProvider.GA4]: EVENT_NAMES.TAP_JOIN_BOARD,
    [EventProvider.Repro]: EVENT_NAMES.TAP_JOIN_BOARD,
  },
  COMPLETE_SEARCH_USER: {
    [EventProvider.GA4]: EVENT_NAMES.COMPLETE_SEARCH_USER,
    [EventProvider.Repro]: EVENT_NAMES.COMPLETE_SEARCH_USER,
  },
  TAP_VIDEOCALL_RANKING: {
    [EventProvider.GA4]: EVENT_NAMES.TAP_VIDEOCALL_RANKING,
    [EventProvider.Repro]: EVENT_NAMES.TAP_VIDEOCALL_RANKING,
  },
  TAP_VOICECALL_RANKING: {
    [EventProvider.GA4]: EVENT_NAMES.TAP_VOICECALL_RANKING,
    [EventProvider.Repro]: EVENT_NAMES.TAP_VOICECALL_RANKING,
  },
  TAP_DUMMY_MESSAGE: {
    [EventProvider.GA4]: EVENT_NAMES.TAP_DUMMY_MESSAGE,
    [EventProvider.Repro]: EVENT_NAMES.TAP_DUMMY_MESSAGE,
  },
  COMPLETE_PURCHASE_VIDEO_GALLERY: {
    [EventProvider.GA4]: EVENT_NAMES.COMPLETE_PURCHASE_VIDEO_GALLERY,
    [EventProvider.Repro]: EVENT_NAMES.COMPLETE_PURCHASE_VIDEO_GALLERY,
  },
  COMPLETE_PURCHASE_IMAGE_GALLERY: {
    [EventProvider.GA4]: EVENT_NAMES.COMPLETE_PURCHASE_IMAGE_GALLERY,
    [EventProvider.Repro]: EVENT_NAMES.COMPLETE_PURCHASE_IMAGE_GALLERY,
  },
  TAP_ADD_BOOKMARK: {
    [EventProvider.GA4]: EVENT_NAMES.TAP_ADD_BOOKMARK,
    [EventProvider.Repro]: EVENT_NAMES.TAP_ADD_BOOKMARK,
  },
  TAP_FAVORITE: {
    [EventProvider.GA4]: EVENT_NAMES.TAP_FAVORITE,
    [EventProvider.Repro]: EVENT_NAMES.TAP_FAVORITE,
  },
  TAP_JOIN_RANKING: {
    [EventProvider.GA4]: EVENT_NAMES.TAP_JOIN_RANKING,
    [EventProvider.Repro]: EVENT_NAMES.TAP_JOIN_RANKING,
  },
  COMPLETE_SEND_IMAGE: {
    [EventProvider.GA4]: EVENT_NAMES.COMPLETE_SEND_IMAGE,
    [EventProvider.Repro]: EVENT_NAMES.COMPLETE_SEND_IMAGE,
  },
  GET_NOTIFICATION_BONUS: {
    [EventProvider.GA4]: EVENT_NAMES.GET_NOTIFICATION_BONUS,
    [EventProvider.Repro]: EVENT_NAMES.GET_NOTIFICATION_BONUS,
  },
  TAP_ADD_BLOCK: {
    [EventProvider.GA4]: EVENT_NAMES.TAP_ADD_BLOCK,
    [EventProvider.Repro]: EVENT_NAMES.TAP_ADD_BLOCK,
  },
  TAP_REMOVE_BLOCK: {
    [EventProvider.GA4]: EVENT_NAMES.TAP_REMOVE_BLOCK,
    [EventProvider.Repro]: EVENT_NAMES.TAP_REMOVE_BLOCK,
  },
  COMPLETE_ADD_REPORT: {
    [EventProvider.GA4]: EVENT_NAMES.COMPLETE_ADD_REPORT,
    [EventProvider.Repro]: EVENT_NAMES.COMPLETE_ADD_REPORT,
  },
  COMPLETE_TIMELINE_COMMENT: {
    [EventProvider.GA4]: EVENT_NAMES.COMPLETE_TIMELINE_COMMENT,
    [EventProvider.Repro]: EVENT_NAMES.COMPLETE_TIMELINE_COMMENT,
  },
  COMPLETE_TIMELINE_LIKE: {
    [EventProvider.GA4]: EVENT_NAMES.COMPLETE_TIMELINE_LIKE,
    [EventProvider.Repro]: EVENT_NAMES.COMPLETE_TIMELINE_LIKE,
  },
  COMPLETE_TIMELINE_POST: {
    [EventProvider.GA4]: EVENT_NAMES.COMPLETE_TIMELINE_POST,
    [EventProvider.Repro]: EVENT_NAMES.COMPLETE_TIMELINE_POST,
  },
  TAP_REGISTER_BANNER_ON_PROFILE: {
    [EventProvider.GA4]: EVENT_NAMES.TAP_REGISTER_BANNER_ON_PROFILE,
    [EventProvider.Repro]: EVENT_NAMES.TAP_REGISTER_BANNER_ON_PROFILE,
  },
  TAP_LOVENSE_ROULETTE_BUTTON: {
    [EventProvider.GA4]: EVENT_NAMES.TAP_LOVENSE_ROULETTE_BUTTON,
    [EventProvider.Repro]: EVENT_NAMES.TAP_LOVENSE_ROULETTE_BUTTON,
  },
  // 購入ページのコースクリックイベント（遷移元トラッキング用）
  CLICK_POINT_COURSE: {
    [EventProvider.GA4]: EVENT_NAMES.CLICK_POINT_COURSE,
    [EventProvider.Repro]: EVENT_NAMES.CLICK_POINT_COURSE,
  },
  CLICK_BONUS_POINT_COURSE: {
    [EventProvider.GA4]: EVENT_NAMES.CLICK_BONUS_POINT_COURSE,
    [EventProvider.Repro]: EVENT_NAMES.CLICK_BONUS_POINT_COURSE,
  },

  // ライブ配信録画プレビュー関連
  TAP_PREVIEW_WATCH_BUTTON: {
    [EventProvider.GA4]: EVENT_NAMES.TAP_PREVIEW_WATCH_BUTTON,
    [EventProvider.Repro]: EVENT_NAMES.TAP_PREVIEW_WATCH_BUTTON,
  },
  TAP_PREVIEW_JOIN_BUTTON: {
    [EventProvider.GA4]: EVENT_NAMES.TAP_PREVIEW_JOIN_BUTTON,
    [EventProvider.Repro]: EVENT_NAMES.TAP_PREVIEW_JOIN_BUTTON,
  },

  // ホーム画面からのビデオ通話確認モーダル
  TAP_VIDEO_CALL_CONFIRM_START: {
    [EventProvider.GA4]: EVENT_NAMES.TAP_VIDEO_CALL_CONFIRM_START,
    [EventProvider.Repro]: EVENT_NAMES.TAP_VIDEO_CALL_CONFIRM_START,
  },

  // レビュー関連
  TAP_RECOMMENDATION_BUTTON: {
    [EventProvider.GA4]: EVENT_NAMES.TAP_RECOMMENDATION_BUTTON,
    [EventProvider.Repro]: EVENT_NAMES.TAP_RECOMMENDATION_BUTTON,
  },
  COMPLETE_SUBMIT_REVIEW: {
    [EventProvider.GA4]: EVENT_NAMES.COMPLETE_SUBMIT_REVIEW,
    [EventProvider.Repro]: EVENT_NAMES.COMPLETE_SUBMIT_REVIEW,
  },

  // オンボーディングクレカ登録バナー
  TAP_ONBOARDING_CREDIT_BANNER: {
    [EventProvider.GA4]: EVENT_NAMES.TAP_ONBOARDING_CREDIT_BANNER,
    [EventProvider.Repro]: EVENT_NAMES.TAP_ONBOARDING_CREDIT_BANNER,
  },
} as const satisfies Record<string, EventTokenConfig>;

/**
 * KeyEvent（コンバージョンイベント）の定義
 * これらのイベントには gclid と client_id が付与される
 */
export const KEY_EVENTS = [
  event.sign_up[EventProvider.GA4]!,
  event.purchase[EventProvider.GA4]!,
  event.COMPLETE_SEND_MESSAGE[EventProvider.GA4]!,
  event.START_VIDEO_CALL[EventProvider.GA4]!,
] as const;

export type KeyEvent = (typeof KEY_EVENTS)[number];

/**
 * 指定されたイベント名がKeyEventかどうかを判定
 */
export function isKeyEvent(eventName: string): boolean {
  return (KEY_EVENTS as readonly string[]).includes(eventName);
}
