export const JamboApiErrors = {
  INVALID_TOKEN: 3,
  INVALID_PARAMETER: 'INVALID_PARAMETER',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  WRONG_DATA_FORMAT: 'WRONG_DATA_FORMAT',
  EMAIL_REGISTED: 'EMAIL_REGISTED',
  INVALID_USER_NAME: 'INVALID_USER_NAME',
  FAILED_ADD_REGISTER_BONUS: 'FAILED_ADD_REGISTER_BONUS',
  ALREADY_ADDED_BLOCK: 'ALREADY_ADDED_BLOCK',
  NOT_ENOUGHT_POINT: 'NOT_ENOUGHT_POINT',
} as const;
